import { Book, MasterData } from './types';

const RAW_IMPORTED_BOOKS: Book[] = [
  {
    "bookId": "1",
    "bookName": "સૌરાષ્ટ્રની રસધાર (ભાગ ૧-૫)",
    "author": "ઝવેરચંદ મેઘાણી",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "લોકસાહિત્ય / વાર્તાઓ",
    "language": "ગુજરાતી",
    "edition": "15th Edition",
    "yearPublished": "1927",
    "isbn": "978-81-8461-101-2",
    "rate": 250,
    "bookType": "New Hard copy",
    "remarks1": "અમર લોકવાર્તાઓનો સંગ્રહ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "2",
    "bookName": "પાટણની પ્રભુતા",
    "author": "કનૈયાલાલ મુનશી",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "ઐતિહાસિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "20th Edition",
    "yearPublished": "1916",
    "isbn": "978-81-8461-102-9",
    "rate": 300,
    "bookType": "Average Condition",
    "remarks1": "પાટણ સામ્રાજ્ય આધારિત પ્રખ્યાત નવલકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "3",
    "bookName": "ગુજરાતનો નાથ",
    "author": "કનૈયાલાલ મુનશી",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "ઐતિહાસિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "18th Edition",
    "yearPublished": "1917",
    "isbn": "978-81-8461-103-6",
    "rate": 320,
    "bookType": "Digital PDF",
    "remarks1": "સિદ્ધરાજ જયસિંહ કાળની કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "4",
    "bookName": "રાજાધિરાજ",
    "author": "કનૈયાલાલ મુનશી",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "ઐતિહાસિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "16th Edition",
    "yearPublished": "1922",
    "isbn": "978-81-8461-104-3",
    "rate": 350,
    "bookType": "Digital Epub",
    "remarks1": "મુનશી ત્રિપુટીની અંતિમ નવલકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "5",
    "bookName": "સરસ્વતીચંદ્ર (ભાગ ૧ થી ૪)",
    "author": "ગોવર્ધનરામ ત્રિપાઠી",
    "translator": "મૂળ",
    "publisher": "એન. એમ. ત્રિપાઠી પ્રા. લિ.",
    "category": "સામાજિક મહાનવલકથા",
    "language": "ગુજરાતી",
    "edition": "25th Edition",
    "yearPublished": "1887",
    "isbn": "978-81-8461-105-0",
    "rate": 800,
    "bookType": "New Hard copy",
    "remarks1": "ગુજરાતી સાહિત્યની પ્રથમ મહાનવલકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "6",
    "bookName": "માનવીની ભવાઈ",
    "author": "પન્નાલાલ પટેલ",
    "translator": "મૂળ",
    "publisher": "સાધના પ્રકાશન",
    "category": "જ્ઞાનપીઠ પુરસ્કૃત નવલકથા",
    "language": "ગુજરાતી",
    "edition": "22nd Edition",
    "yearPublished": "1947",
    "isbn": "978-81-8461-106-7",
    "rate": 280,
    "bookType": "Old Hard copy",
    "remarks1": "છપ્પનિયા દુષ્કાળ પૃષ્ઠભૂમિ કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "7",
    "bookName": "મળેલા જીવ",
    "author": "પન્નાલાલ પટેલ",
    "translator": "મૂળ",
    "publisher": "સાધના પ્રકાશન",
    "category": "પ્રણય નવલકથા",
    "language": "ગુજરાતી",
    "edition": "19th Edition",
    "yearPublished": "1941",
    "isbn": "978-81-8461-107-4",
    "rate": 220,
    "bookType": "Digital PDF",
    "remarks1": "કાંજી અને જીવીની અમર પ્રેમકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "8",
    "bookName": "કુરુક્ષેત્ર",
    "author": "મનુભાઈ પંચોળી 'દર્શક'",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "ચિંતનાત્મક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "12th Edition",
    "yearPublished": "1975",
    "isbn": "978-81-8461-108-1",
    "rate": 340,
    "bookType": "Digital DOCX",
    "remarks1": "મહાભારત આધારિત મનોવૈજ્ઞાનિક વિશ્લેષણ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "9",
    "bookName": "સોક્રેટીસ",
    "author": "મનુભાઈ પંચોળી 'દર્શક'",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "તત્ત્વચિંતન નવલકથા",
    "language": "ગુજરાતી",
    "edition": "14th Edition",
    "yearPublished": "1974",
    "isbn": "978-81-8461-109-8",
    "rate": 310,
    "bookType": "Digital PDF",
    "remarks1": "એથેન્સના મહાન તત્ત્વજ્ઞાની સોક્રેટીસનું જીવન",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "10",
    "bookName": "ઝેર તો પીધાં છે જાણી જાણી (ભાગ ૧-૩)",
    "author": "મનુભાઈ પંચોળી 'દર્શક'",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "સામાજિક ચિંતન નવલકથા",
    "language": "ગુજરાતી",
    "edition": "15th Edition",
    "yearPublished": "1952",
    "isbn": "978-81-8461-110-4",
    "rate": 550,
    "bookType": "New Hard copy",
    "remarks1": "મહાત્મા ગાંધીજીના મૂલ્યોથી પ્રેરાયેલ કૃતિ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "11",
    "bookName": "સત્યના પ્રયોગો અથવા આત્મકથા",
    "author": "મહાત્મા ગાંધી",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "language": "ગુજરાતી",
    "edition": "50th Edition",
    "yearPublished": "1927",
    "isbn": "978-81-7229-001-6",
    "rate": 200,
    "bookType": "New Hard copy",
    "remarks1": "ગાંધીજીની વિશ્વપ્રસિદ્ધ આત્મકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "12",
    "bookName": "હિન્દ સ્વરાજ",
    "author": "મહાત્મા ગાંધી",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "રાજકીય / ચિંતન સાહિત્ય",
    "language": "ગુજરાતી",
    "edition": "30th Edition",
    "yearPublished": "1909",
    "isbn": "978-81-7229-015-3",
    "rate": 90,
    "bookType": "Digital PDF",
    "remarks1": "ગાંધીજીનું ક્રાંતિકારી વૈચારિક પુસ્તક",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "13",
    "bookName": "દિવ્યચક્ષુ",
    "author": "રમણલાલ વ. દેસાઈ",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "સામાજિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1932",
    "isbn": "978-81-8461-113-5",
    "rate": 260,
    "bookType": "Digital Epub",
    "remarks1": "સ્વાતંત્ર્ય સંગ્રામ સમયની લોકપ્રિય કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "14",
    "bookName": "ભારેલો અગ્નિ",
    "author": "રમણલાલ વ. દેસાઈ",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "ઐતિહાસિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "14th Edition",
    "yearPublished": "1935",
    "isbn": "978-81-8461-114-2",
    "rate": 290,
    "bookType": "Average Condition",
    "remarks1": "૧૮૫૭ના સ્વાતંત્ર્ય વિપ્લવ આધારિત કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "15",
    "bookName": "ગુજરાતના ઘડવૈયા",
    "author": "કાકાસાહેબ કાલેલકર",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "ઇતિહાસ / ચરિત્ર સાહિત્ય",
    "language": "ગુજરાતી",
    "edition": "8th Edition",
    "yearPublished": "1945",
    "isbn": "978-81-8461-115-9",
    "rate": 240,
    "bookType": "Old Hard copy",
    "remarks1": "ગુજરાતની મહાન વિભૂતિઓની જીવનગાથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "16",
    "bookName": "સમરાંગણ",
    "author": "ઝવેરચંદ મેઘાણી",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "ઐતિહાસિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "12th Edition",
    "yearPublished": "1938",
    "isbn": "978-81-8461-116-6",
    "rate": 210,
    "bookType": "Digital PDF",
    "remarks1": "ભૂચર મોરીના યુદ્ધ આધારિત ઐતિહાસિક કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "17",
    "bookName": "સોરઠ તારા વહેતાં પાણી",
    "author": "ઝવેરચંદ મેઘાણી",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "સામાજિક / લોકજીવન નવલકથા",
    "language": "ગુજરાતી",
    "edition": "16th Edition",
    "yearPublished": "1937",
    "isbn": "978-81-8461-117-3",
    "rate": 270,
    "bookType": "New Hard copy",
    "remarks1": "સોરઠ ધરાના જનજીવન અને સંસ્કારોની ઝાંખી",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "18",
    "bookName": "વેવિશાળ",
    "author": "ઝવેરચંદ મેઘાણી",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "સામાજિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "18th Edition",
    "yearPublished": "1939",
    "isbn": "978-81-8461-118-0",
    "rate": 230,
    "bookType": "Digital Epub",
    "remarks1": "મધ્યમવર્ગીય જીવન મૂલ્યોની અદ્ભુત રજૂઆત",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "19",
    "bookName": "કંકાવટી",
    "author": "ઝવેરચંદ મેઘાણી",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "લોકવ્રત વાર્તાઓ",
    "language": "ગુજરાતી",
    "edition": "11th Edition",
    "yearPublished": "1928",
    "isbn": "978-81-8461-119-7",
    "rate": 180,
    "bookType": "Digital PDF",
    "remarks1": "ગુજરાતની સ્ત્રીઓના વ્રત અને તહેવારોની વાર્તાઓ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "20",
    "bookName": "001 Urdu Hindi Shabdkosh",
    "author": "રાષ્ટ્રભાષા પ્રચાર સમિતિ",
    "translator": "સંકલિત",
    "publisher": "પ્રભાત પ્રકાશન",
    "category": "શબ્દકોશ / ભાષાંતર",
    "language": "હિન્દી / ઉર્દૂ",
    "edition": "1st Edition",
    "yearPublished": "1959",
    "isbn": "978-81-8461-120-3",
    "rate": 450,
    "bookType": "Digital PDF",
    "remarks1": "ઉર્દૂ અને હિન્દી શબ્દોનો પ્રમાણભૂત કોશ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "21",
    "bookName": "Urdu for Pleasure for Ghazal Love",
    "author": "વેસ્ટલેન્ડ કલેક્શન",
    "translator": "Original",
    "publisher": "Westland Publications",
    "category": "કાવ્ય સાહિત્ય / ગઝલ",
    "language": "ઇંગ્લીશ / ઉર્દૂ",
    "edition": "4th Edition",
    "yearPublished": "1992",
    "isbn": "81-900253-0-9",
    "rate": 350,
    "bookType": "Digital Epub",
    "remarks1": "ગઝલો અને ઉર્દૂ શાયરીનો સુંદર સંગ્રહ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "22",
    "bookName": "અમૃતા",
    "author": "રઘુવીર ચૌધરી",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "જ્ઞાનપીઠ પુરસ્કૃત નવલકથા",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1965",
    "isbn": "978-81-8461-122-7",
    "rate": 260,
    "bookType": "Digital PDF",
    "remarks1": "માનવ સંબંધો અને અસ્તિત્વવાદની સુંદર કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "23",
    "bookName": "ઉપરવાસ કથાત્રયી",
    "author": "રઘુવીર ચૌધરી",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "સામાજિક ત્રિલોગી",
    "language": "ગુજરાતી",
    "edition": "8th Edition",
    "yearPublished": "1975",
    "isbn": "978-81-8461-123-4",
    "rate": 480,
    "bookType": "New Hard copy",
    "remarks1": "સાહિત્ય અકાદમી પુરસ્કૃત ગ્રામીણ કથાત્રયી",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "24",
    "bookName": "સાત પગલાં આકાશમાં",
    "author": "કુંદનિકા કાપડિયા",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "નારીવાદી નવલકથા",
    "language": "ગુજરાતી",
    "edition": "25th Edition",
    "yearPublished": "1984",
    "isbn": "978-81-8461-124-1",
    "rate": 320,
    "bookType": "New Hard copy",
    "remarks1": "સ્ત્રી ચેતના અને આત્મસન્માનની ક્રાંતિકારી કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "25",
    "bookName": "અગનપંખી",
    "author": "ધ્રુવ ભટ્ટ",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "સાહસ નવલકથા",
    "language": "ગુજરાતી",
    "edition": "9th Edition",
    "yearPublished": "2002",
    "isbn": "978-81-8461-125-8",
    "rate": 240,
    "bookType": "Digital PDF",
    "remarks1": "પ્રકૃતિ અને માનવ સંવેદનાનો અનોખો મેળાપ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "26",
    "bookName": "તત્ત્વમસિ",
    "author": "ધ્રુવ ભટ્ટ",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "અધ્યાત્મ અને પ્રકૃતિ કથા",
    "language": "ગુજરાતી",
    "edition": "15th Edition",
    "yearPublished": "1998",
    "isbn": "978-81-8461-126-5",
    "rate": 280,
    "bookType": "Digital Epub",
    "remarks1": "નર્મદા કિનારાના આદિવાસી જીવન અને સુંદરતા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "27",
    "bookName": "સમુદ્રાન્તિકે",
    "author": "ધ્રુવ ભટ્ટ",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "પ્રવાસ અને દરિયાઈ કથા",
    "language": "ગુજરાતી",
    "edition": "12th Edition",
    "yearPublished": "1993",
    "isbn": "978-81-8461-127-2",
    "rate": 250,
    "bookType": "Digital PDF",
    "remarks1": "દરિયાકંઠાના ખારવા અને જીવન સંસ્કૃતિ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "28",
    "bookName": "કર્ણઘેલો",
    "author": "નંદશંકર તુલજાશંકર મહેતા",
    "translator": "મૂળ",
    "publisher": "એન. એમ. ત્રિપાઠી",
    "category": "પ્રથમ ઐતિહાસિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "20th Edition",
    "yearPublished": "1866",
    "isbn": "978-81-8461-128-9",
    "rate": 220,
    "bookType": "Old Hard copy",
    "remarks1": "ગુજરાતી ભાષાની સર્વપ્રથમ નવલકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "29",
    "bookName": "ભદ્રંભદ્ર",
    "author": "રમણભાઈ નીલકંઠ",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "હાસ્ય નવલકથા",
    "language": "ગુજરાતી",
    "edition": "14th Edition",
    "yearPublished": "1900",
    "isbn": "978-81-8461-129-6",
    "rate": 190,
    "bookType": "Digital PDF",
    "remarks1": "ગુજરાતી સાહિત્યની કલાસિક હાસ્ય નવલકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "30",
    "bookName": "૧૦૧ પંચતંત્ર વાર્તાઓ",
    "author": "વિષ્ણુ શર્મા",
    "translator": "અનુ. સંકલિત",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "બાળ સાહિત્ય / બોધકથાઓ",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "2018",
    "isbn": "978-81-8461-130-2",
    "rate": 180,
    "bookType": "New Hard copy",
    "remarks1": "બાળકો માટે શિક્ષાત્મક રોચક વાર્તાઓ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "31",
    "bookName": "ગંગોત્રી",
    "author": "ઉમાશંકર જોશી",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "કાવ્ય સંગ્રહ",
    "language": "ગુજરાતી",
    "edition": "12th Edition",
    "yearPublished": "1935",
    "isbn": "978-81-8461-131-9",
    "rate": 170,
    "bookType": "Digital PDF",
    "remarks1": "ઉમાશંકર જોશીનો પ્રથમ કાવ્યસંગ્રહ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "32",
    "bookName": "નિશીથ",
    "author": "ઉમાશંકર જોશી",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "જ્ઞાનપીઠ પુરસ્કૃત કાવ્યસંગ્રહ",
    "language": "ગુજરાતી",
    "edition": "15th Edition",
    "yearPublished": "1939",
    "isbn": "978-81-8461-132-6",
    "rate": 210,
    "bookType": "Digital Epub",
    "remarks1": "૧૯૬૭માં જ્ઞાનપીઠ એવોર્ડ મેળવનાર કાવ્યસંગ્રહ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "33",
    "bookName": "વાસુકી",
    "author": "ઉમાશંકર જોશી",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "નાટક / એકાંકી",
    "language": "ગુજરાતી",
    "edition": "8th Edition",
    "yearPublished": "1947",
    "isbn": "978-81-8461-133-3",
    "rate": 160,
    "bookType": "Digital PDF",
    "remarks1": "નાટ્ય કલા અને સંવાદોથી સમૃદ્ધ કૃતિ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "34",
    "bookName": "After the Prophet - The Epic Story",
    "author": "Lesley Hazleton",
    "translator": "Original",
    "publisher": "Doubleday & Co",
    "category": "ઇતિહાસ / ધર્મ અભ્યાસ",
    "language": "ઇંગ્લીશ",
    "edition": "1st Edition",
    "yearPublished": "2009",
    "isbn": "978-0-285-53209-9",
    "rate": 450,
    "bookType": "Digital PDF",
    "remarks1": "ઇસ્લામના ઇતિહાસ વિષયક વિસ્તૃત સંશોધન ગ્રંથ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "35",
    "bookName": "ALL ADOBE CC PREMIUM BUNDLE",
    "author": "ટેકનોલોજી મેન્યુઅલ",
    "translator": "Original",
    "publisher": "Digital Book House",
    "category": "કોમ્પ્યુટર / ટેકનોલોજી",
    "language": "ઇંગ્લીશ",
    "edition": "2024 Edition",
    "yearPublished": "2024",
    "isbn": "N/A",
    "rate": 990,
    "bookType": "Digital PDF",
    "remarks1": "સોફ્ટવેર ટ્યુટોરીયલ અને ડિઝાઇન ગાઇડ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "36",
    "bookName": "છિન્નપત્ર",
    "author": "સુરેશ જોશી",
    "translator": "મૂળ",
    "publisher": "પ્રત્યક્ષ પ્રકાશન",
    "category": "આધુનિકતાવાદી નવલકથા",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1965",
    "isbn": "978-81-8461-136-4",
    "rate": 180,
    "bookType": "Digital Epub",
    "remarks1": "ગુજરાતી સાહિત્યમાં પ્રયોગશીલ આધુનિક કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "37",
    "bookName": "The Constitution of India (ભારતનું બંધારણ)",
    "author": "ડૉ. બી. આર. આંબેડકર સંકલિત",
    "translator": "ગુજરાતી અનુવાદ",
    "publisher": "સરકારી પ્રકાશન વિભાગ",
    "category": "કાયદો / બંધારણ",
    "language": "ગુજરાતી / ઇંગ્લીશ",
    "edition": "4th Edition",
    "yearPublished": "2011",
    "isbn": "978-81-8461-137-1",
    "rate": 600,
    "bookType": "Digital PDF",
    "remarks1": "ભારતના બંધારણનું અધિકૃત પરિશિષ્ટ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "38",
    "bookName": "હાસ્યમંજરી",
    "author": "જ્યોતીન્દ્ર દવે",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "હાસ્ય નિબંધો",
    "language": "ગુજરાતી",
    "edition": "11th Edition",
    "yearPublished": "1958",
    "isbn": "978-81-8461-138-8",
    "rate": 200,
    "bookType": "Digital PDF",
    "remarks1": "હાસ્યસમ્રાટ જ્યોતીન્દ્ર દવેના શ્રેષ્ઠ લેખો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "39",
    "bookName": "પાનકોરના નાકેથી",
    "author": "જ્યોતીન્દ્ર દવે",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "હાસ્ય કથા સંગ્રહ",
    "language": "ગુજરાતી",
    "edition": "9th Edition",
    "yearPublished": "1968",
    "isbn": "978-81-8461-139-5",
    "rate": 190,
    "bookType": "Digital DOCX",
    "remarks1": "અમદાવાદી શેરી જીવનના રમૂજી અનુભવો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "40",
    "bookName": "ધરતીનો ધબકાર",
    "author": "ઈશ્વર પેટલીકર",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "સામાજિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "12th Edition",
    "yearPublished": "1955",
    "isbn": "978-81-8461-140-1",
    "rate": 260,
    "bookType": "Digital PDF",
    "remarks1": "ચરોતર પ્રદેશના ગ્રામીણ સંસ્કારોની કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "41",
    "bookName": "જનમટીપ",
    "author": "ઈશ્વર પેટલીકર",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "સામાજિક સંઘર્ષ કથા",
    "language": "ગુજરાતી",
    "edition": "16th Edition",
    "yearPublished": "1944",
    "isbn": "978-81-8461-141-8",
    "rate": 240,
    "bookType": "Average Condition",
    "remarks1": "ચંદા અને ભીમા વચ્ચેના સાહસ અને પ્રેમની કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "42",
    "bookName": "Eye witness Hunter",
    "author": "ક્રાઇમ સીરીઝ સંકલન",
    "translator": "Original",
    "publisher": "BlueRose Publishers",
    "category": "સસ્પેન્સ / થ્રિલર",
    "language": "ઇંગ્લીશ",
    "edition": "1st Edition",
    "yearPublished": "2021",
    "isbn": "978-93-93795-46-5",
    "rate": 299,
    "bookType": "Digital PDF",
    "remarks1": "રોમાંચક જાસૂસી અને ક્રાઇમ નવલકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "43",
    "bookName": "લોહીની સગાઈ",
    "author": "ઈશ્વર પેટલીકર",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "ટૂંકી વાર્તાઓ",
    "language": "ગુજરાતી",
    "edition": "14th Edition",
    "yearPublished": "1951",
    "isbn": "978-81-8461-143-2",
    "rate": 180,
    "bookType": "Digital Epub",
    "remarks1": "અમૃતકાકી અને મંગુના વાત્સલ્યપ્રેમની અમર વાર્તા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "44",
    "bookName": "મારી હકીકત",
    "author": "કવિ નર્મદ",
    "translator": "મૂળ",
    "publisher": "કવિ નર્મદ યુગાવર્ત ટ્રસ્ટ",
    "category": "પ્રથમ ગુજરાતી આત્મકથા",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1866",
    "isbn": "978-81-8461-144-9",
    "rate": 200,
    "bookType": "Old Hard copy",
    "remarks1": "ગુજરાતી સાહિત્યની સર્વપ્રથમ આત્મકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "45",
    "bookName": "ગુજરાતી ભાષાનો બૃહદ્ કોશ",
    "author": "ગુજરાત વિદ્યાપીઠ",
    "translator": "સંકલિત",
    "publisher": "ગુજરાત વિદ્યાપીઠ ગ્રંથાલય",
    "category": "સંદર્ભ ગ્રંથ / કોશ",
    "language": "ગુજરાતી",
    "edition": "5th Edition",
    "yearPublished": "1995",
    "isbn": "978-81-8461-145-6",
    "rate": 1200,
    "bookType": "New Hard copy",
    "remarks1": "ગુજરાતી શુદ્ધ જોડણી અને અર્થકોશ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "46",
    "bookName": "ભગવદ્ગોમંડલ (૧ થી ૯ ભાગ)",
    "author": "મહારાજા ભગવતસિંહજી",
    "translator": "સંકલિત",
    "publisher": "પ્રવીણ પ્રકાશન",
    "category": "વિશ્વકોશ / જ્ઞાનકોશ",
    "language": "ગુજરાતી",
    "edition": "4th Edition",
    "yearPublished": "1944",
    "isbn": "978-81-8461-146-3",
    "rate": 4500,
    "bookType": "New Hard copy",
    "remarks1": "ગુજરાતી ભાષાનો અજોડ જ્ઞાનકોશ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "47",
    "bookName": "Handbook on Family Pension",
    "author": "Government of India",
    "translator": "Official",
    "publisher": "Government Publications",
    "category": "કાયદો અને નિયમો",
    "language": "ઇંગ્લીશ",
    "edition": "1st Edition",
    "yearPublished": "2020",
    "isbn": "N/A",
    "rate": 350,
    "bookType": "Digital PDF",
    "remarks1": "પેન્શન અને ગ્રેચ્યુઇટી નિયમોની માર્ગદર્શિકા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "48",
    "bookName": "ગીતાંજલિ",
    "author": "રવીન્દ્રનાથ ટાગોર",
    "translator": "ઝવેરચંદ મેઘાણી",
    "publisher": "ગૂર્જર સાહિત્ય ભવન",
    "category": "નોબેલ વિજેતા કાવ્યસંગ્રહ",
    "language": "ગુજરાતી",
    "edition": "12th Edition",
    "yearPublished": "1910",
    "isbn": "978-81-8461-148-7",
    "rate": 220,
    "bookType": "Digital Epub",
    "remarks1": "રવીન્દ્રનાથ ટાગોરના અમર કાવ્યોનો સંવાદ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "49",
    "bookName": "ચિંતન કણિકા",
    "author": "સ્વામી સચ્ચિદાનંદ",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "અધ્યાત્મ અને સમાજ",
    "language": "ગુજરાતી",
    "edition": "15th Edition",
    "yearPublished": "1990",
    "isbn": "978-81-8461-149-4",
    "rate": 180,
    "bookType": "Digital PDF",
    "remarks1": "જીવન સુધારણા અને વૈજ્ઞાનિક દ્રષ્ટિકોણ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "50",
    "bookName": "મારા અનુભવો",
    "author": "સ્વામી સચ્ચિદાનંદ",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર સાહિત્ય ભવન",
    "category": "જીવન અનુભવ / આત્મકથા",
    "language": "ગુજરાતી",
    "edition": "18th Edition",
    "yearPublished": "1988",
    "isbn": "81-288-0711-0",
    "rate": 300,
    "bookType": "New Hard copy",
    "remarks1": "સ્વામીજીના પ્રેરણાદાયી જીવન અનુભવો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "51",
    "bookName": "ધર્મોત્થાન",
    "author": "સ્વામી વિવેકાનંદ",
    "translator": "શ્રી રામકૃષ્ણ આશ્રમ",
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "category": "ધર્મ અને ચિંતન",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1975",
    "isbn": "978-81-8461-151-7",
    "rate": 150,
    "bookType": "Digital PDF",
    "remarks1": "યુવાનો માટે સ્વામીજીનું ક્રાંતિકારી આહ્વાન",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "52",
    "bookName": "ભગવદ્ ગીતા તાત્પર્ય",
    "author": "સ્વામી ચિન્મયાનંદ",
    "translator": "ચિન્મય મિશન",
    "publisher": "ચિન્મય પ્રકાશન",
    "category": "વેદાંત / ગીતા ભાષ્ય",
    "language": "ગુજરાતી",
    "edition": "6th Edition",
    "yearPublished": "1982",
    "isbn": "978-81-8461-152-4",
    "rate": 400,
    "bookType": "Digital Epub",
    "remarks1": "શ્રીમદ્ ભગવદ્ ગીતાનું સુગમ વિવેચન",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "53",
    "bookName": "યુગદ્રષ્ટા મહાત્મા",
    "author": "કાકાસાહેબ કાલેલકર",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "ચરિત્ર સાહિત્ય",
    "language": "ગુજરાતી",
    "edition": "8th Edition",
    "yearPublished": "1960",
    "isbn": "978-81-8461-153-1",
    "rate": 220,
    "bookType": "Digital PDF",
    "remarks1": "ગાંધીજી સાથેના અનુભવોનું સંસ્મરણ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "54",
    "bookName": "Khullam Khulla Rishi Kapoor",
    "author": "MEENA IYER",
    "translator": "Original",
    "publisher": "HarperCollins Publishers",
    "category": "બોલિવૂડ / આત્મકથા",
    "language": "ઇંગ્લીશ",
    "edition": "1st Edition",
    "yearPublished": "2017",
    "isbn": "978-93-5264-307-3",
    "rate": 399,
    "bookType": "Digital PDF",
    "remarks1": "અભિનેતા ઋષિ કપૂરની સંવેદનશીલ આત્મકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "55",
    "bookName": "ક્યા કરેં ક્યા ના કરેં",
    "author": "ડૉ. આઈ કે વીજળીવાળા",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "બાળ ઉછેર / પ્રેરણાદાયી",
    "language": "ગુજરાતી",
    "edition": "12th Edition",
    "yearPublished": "2015",
    "isbn": "978-81-8461-155-5",
    "rate": 250,
    "bookType": "Digital PDF",
    "remarks1": "માતાપિતા અને બાળકો માટે ઉપયોગી માર્ગદર્શન",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "56",
    "bookName": "મોતીચારો (ભાગ ૧ થી ૫)",
    "author": "ડૉ. આઈ કે વીજળીવાળા",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "પ્રેરણાદાયી પ્રસંગો",
    "language": "ગુજરાતી",
    "edition": "20th Edition",
    "yearPublished": "2012",
    "isbn": "978-81-8461-156-2",
    "rate": 650,
    "bookType": "New Hard copy",
    "remarks1": "જીવનમાં ઉમંગ અને હકારાત્મકતા પૂરતી વાર્તાઓ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "57",
    "bookName": "સાયન્સ અને અધ્યાત્મ",
    "author": "ગુણવંત શાહ",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "વૈજ્ઞાનિક ચિંતન",
    "language": "ગુજરાતી",
    "edition": "9th Edition",
    "yearPublished": "2005",
    "isbn": "978-81-8461-157-9",
    "rate": 270,
    "bookType": "Digital Epub",
    "remarks1": "વિજ્ઞાન અને અગમ્ય ચેતનાનો સમન્વય",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "58",
    "bookName": "કાર્ડિયોગ્રામ",
    "author": "ગુણવંત શાહ",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "ચિંતનાત્મક નિબંધો",
    "language": "ગુજરાતી",
    "edition": "14th Edition",
    "yearPublished": "1997",
    "isbn": "978-81-8461-158-6",
    "rate": 240,
    "bookType": "Digital PDF",
    "remarks1": "સામાજિક વિસંગતતાઓ પર તીક્ષ્ણ કટાક્ષ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "59",
    "bookName": "Pakistan or Partition of India",
    "author": "Dr. B. R. Ambedkar",
    "translator": "Original",
    "publisher": "Thacker and Company",
    "category": "ઇતિહાસ / રાજનીતિ",
    "language": "ઇંગ્લીશ",
    "edition": "1st Edition",
    "yearPublished": "1945",
    "isbn": "978-81-8461-159-3",
    "rate": 500,
    "bookType": "Digital PDF",
    "remarks1": "દેશના ભાગલા સમયની રાજકીય સ્થિતિનું વિશ્લેષણ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "60",
    "bookName": "R.D. Burman The Man, the Music",
    "author": "Anirudha Bhattacharjee",
    "translator": "Original",
    "publisher": "HarperCollins Publishers",
    "category": "સંગીત / જીવની",
    "language": "ઇંગ્લીશ",
    "edition": "1st Edition",
    "yearPublished": "2011",
    "isbn": "9789350290491",
    "rate": 499,
    "bookType": "Digital PDF + Digital Epub",
    "remarks1": "પંચમદાના સંગીત અને જીવનની રોચક સફર",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "61",
    "bookName": "સ્વીટ સોળ",
    "author": "કાજલ ઓઝા વૈદ્ય",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "યુવા નવલકથા",
    "language": "ગુજરાતી",
    "edition": "11th Edition",
    "yearPublished": "2010",
    "isbn": "978-81-8461-161-6",
    "rate": 230,
    "bookType": "Digital PDF",
    "remarks1": "કિશોરાવસ્થાના સંવેદનો અને મનોમંથન",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "62",
    "bookName": "દ્રૌપદી",
    "author": "કાજલ ઓઝા વૈદ્ય",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "પૌરાણિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "16th Edition",
    "yearPublished": "2013",
    "isbn": "978-81-8461-162-3",
    "rate": 320,
    "bookType": "New Hard copy",
    "remarks1": "દ્રૌપદીના દ્રષ્ટિકોણથી મહાભારતની ગાથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "63",
    "bookName": "કૃષ્ણાયન",
    "author": "કાજલ ઓઝા વૈદ્ય",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "અધ્યાત્મ અને કૃષ્ણપ્રેમ",
    "language": "ગુજરાતી",
    "edition": "18th Edition",
    "yearPublished": "2015",
    "isbn": "978-81-8461-163-0",
    "rate": 350,
    "bookType": "New Hard copy",
    "remarks1": "શ્રીકૃષ્ણના જીવનના ઉત્તરાધંની સંવેદનશીલ કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "64",
    "bookName": "SON OF HAMAS",
    "author": "MOSAB HASSAN YOUSEF",
    "translator": "Original",
    "publisher": "SaltRiver Publications",
    "category": "આંતરરાષ્ટ્રીય / જીવની",
    "language": "ઇંગ્લીશ",
    "edition": "1st Edition",
    "yearPublished": "2010",
    "isbn": "978-1-4143-3668-8",
    "rate": 550,
    "bookType": "Digital PDF",
    "remarks1": "મધ્ય પૂર્વના સંઘર્ષો વિશેનો સનસનાટીપૂર્ણ અહેવાલ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "65",
    "bookName": "એક સોનેરી સવાર",
    "author": "ચંદ્રકાંત બક્ષી",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "સામાજિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "8th Edition",
    "yearPublished": "1982",
    "isbn": "978-81-8461-165-4",
    "rate": 210,
    "bookType": "Digital Epub",
    "remarks1": "આધુનિક માનવીના સંબંધોની કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "66",
    "bookName": "THE SECRET - રહસ્ય",
    "author": "Rhonda Byrne",
    "translator": "ગુજરાતી અનુવાદ",
    "publisher": "મંજુલા પબ્લિકેશન",
    "category": "સ્વ-વિકાસ / પ્રેરણાદાયી",
    "language": "ગુજરાતી",
    "edition": "20th Edition",
    "yearPublished": "2008",
    "isbn": "978-81-8322-198-6",
    "rate": 299,
    "bookType": "New Hard copy",
    "remarks1": "આકર્ષણના નિયમ પર આધારિત વિશ્વપ્રસિદ્ધ પુસ્તક",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "67",
    "bookName": "બક્ષીનામા (ભાગ ૧ થી ૩)",
    "author": "ચંદ્રકાંત બક્ષી",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "આત્મકથા / સ્મરણો",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1998",
    "isbn": "978-81-8461-167-8",
    "rate": 600,
    "bookType": "Digital PDF",
    "remarks1": "ચંદ્રકાંત બક્ષીની સ્પષ્ટવક્તા વાળી આત્મકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "68",
    "bookName": "આકાર",
    "author": "ચંદ્રકાંત બક્ષી",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "મનોવૈજ્ઞાનિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "7th Edition",
    "yearPublished": "1963",
    "isbn": "978-81-8461-168-5",
    "rate": 220,
    "bookType": "Digital DOCX",
    "remarks1": "કોલકાતા પૃષ્ઠભૂમિ પર રચાયેલી કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "69",
    "bookName": "પરાજીત",
    "author": "ચંદ્રકાંત બક્ષી",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "સામાજિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "6th Edition",
    "yearPublished": "1958",
    "isbn": "978-81-8461-169-2",
    "rate": 200,
    "bookType": "Average Condition",
    "remarks1": "બક્ષીજીની સર્વપ્રથમ જાણીતી નવલકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "70",
    "bookName": "ઝીરો પોઈન્ટ",
    "author": "ચંદ્રકાંત બક્ષી",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "વિચાર સંકલન / કટાર લેખો",
    "language": "ગુજરાતી",
    "edition": "9th Edition",
    "yearPublished": "1992",
    "isbn": "978-81-8461-170-8",
    "rate": 250,
    "bookType": "Digital PDF",
    "remarks1": "વિવિધ વિષયો પર તીક્ષ્ણ વિચારોનો વૈભવ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "71",
    "bookName": "અનાવૃત",
    "author": "ચંદ્રકાંત બક્ષી",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "નિબંધ સંગ્રહ",
    "language": "ગુજરાતી",
    "edition": "5th Edition",
    "yearPublished": "1988",
    "isbn": "978-81-8461-171-5",
    "rate": 230,
    "bookType": "Old Hard copy",
    "remarks1": "સાહિત્ય અને સમાજ પર નિડર વિચારો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "72",
    "bookName": "હિમાલયનો પ્રવાસ",
    "author": "કાકાસાહેબ કાલેલકર",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "પ્રવાસ સાહિત્ય",
    "language": "ગુજરાતી",
    "edition": "20th Edition",
    "yearPublished": "1924",
    "isbn": "978-81-7229-050-0",
    "rate": 250,
    "bookType": "New Hard copy",
    "remarks1": "ગુજરાતી પ્રવાસ સાહિત્યનો શિખર ગ્રંથ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "73",
    "bookName": "જીવનનો આનંદ",
    "author": "કાકાસાહેબ કાલેલકર",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "લલિત નિબંધો",
    "language": "ગુજરાતી",
    "edition": "14th Edition",
    "yearPublished": "1936",
    "isbn": "8123727380",
    "rate": 220,
    "bookType": "Digital PDF",
    "remarks1": "પ્રકૃતિ અને જીવન સૌંદર્યના સુંદર નિબંધો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "74",
    "bookName": "સ્મરણ યાત્રા",
    "author": "કાકાસાહેબ કાલેલકર",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "બાળપણના સંસ્મરણો",
    "language": "ગુજરાતી",
    "edition": "12th Edition",
    "yearPublished": "1934",
    "isbn": "978-81-8461-174-6",
    "rate": 210,
    "bookType": "Digital Epub",
    "remarks1": "બાળપણની રમૂજી અને પ્રેરક સ્મૃતિઓ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "75",
    "bookName": "પૂર્વરંગ",
    "author": "કાકાસાહેબ કાલેલકર",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "દેશ-વિદેશ પ્રવાસ",
    "language": "ગુજરાતી",
    "edition": "8th Edition",
    "yearPublished": "1953",
    "isbn": "978-81-8461-175-3",
    "rate": 240,
    "bookType": "Digital PDF",
    "remarks1": "પૂર્વના દેશોનો રોચક પ્રવાસ વર્ણન",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "76",
    "bookName": "અક્ષર દેહ",
    "author": "મહાત્મા ગાંધી",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "ગાંધી સાહિત્ય શ્રેણી",
    "language": "ગુજરાતી",
    "edition": "2nd Edition",
    "yearPublished": "1965",
    "isbn": "978-81-8461-176-0",
    "rate": 850,
    "bookType": "New Hard copy",
    "remarks1": "ગાંધીજીના તમામ પત્રો અને લેખોનો મહાકાય સંગ્રહ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "77",
    "bookName": "દક્ષિણ આફ્રિકાના સત્યાગ્રહનો ઇતિહાસ",
    "author": "મહાત્મા ગાંધી",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "ઇતિહાસ / સત્યાગ્રહ",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1924",
    "isbn": "978-81-8461-177-7",
    "rate": 280,
    "bookType": "Digital PDF",
    "remarks1": "સત્યાગ્રહના પ્રયોગોની પ્રથમ ભૂમિકા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "78",
    "bookName": "મંગળ પ્રભાત",
    "author": "મહાત્મા ગાંધી",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "એકાદશ વ્રત ચિંતન",
    "language": "ગુજરાતી",
    "edition": "25th Edition",
    "yearPublished": "1930",
    "isbn": "978-81-8461-178-4",
    "rate": 80,
    "bookType": "Digital DOCX",
    "remarks1": "આશ્રમના વ્રતો અને જીવન નિયમો વિશે ચિંતન",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "79",
    "bookName": "કેળવણીના પાયા",
    "author": "કિશોરલાલ મશરૂવાળા",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "શિક્ષણ / ચિંતન",
    "language": "ગુજરાતી",
    "edition": "6th Edition",
    "yearPublished": "1950",
    "isbn": "978-81-8461-179-1",
    "rate": 160,
    "bookType": "Digital PDF",
    "remarks1": "ગાંધીવાદી શિક્ષણ વિભાવનાઓ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "80",
    "bookName": "અહિંસા અને જીવન",
    "author": "કિશોરલાલ મશરૂવાળા",
    "translator": "મૂળ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "નૈતિક જીવન દર્શન",
    "language": "ગુજરાતી",
    "edition": "5th Edition",
    "yearPublished": "1952",
    "isbn": "978-81-8461-180-7",
    "rate": 150,
    "bookType": "Digital Epub",
    "remarks1": "માનવ ધર્મ અને વ્યવહારિક અહિંસા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "81",
    "bookName": "વિનોબા ભાવે વિચારધારા",
    "author": "વિનોબા ભાવે",
    "translator": "મૂળ",
    "publisher": "સર્વોદય પ્રકાશન",
    "category": "ભૂદાન અને વિચારધારા",
    "language": "ગુજરાતી",
    "edition": "8th Edition",
    "yearPublished": "1960",
    "isbn": "978-81-8461-181-4",
    "rate": 170,
    "bookType": "Digital PDF",
    "remarks1": "ભૂદાન ચળવળ અને ગાંધીવાદી સમાજવાદ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "82",
    "bookName": "ગીતા પ્રવચન",
    "author": "વિનોબા ભાવે",
    "translator": "મૂળ",
    "publisher": "યજ્ઞ પ્રકાશન",
    "category": "ગીતા ભાષ્ય / ચિંતન",
    "language": "ગુજરાતી",
    "edition": "35th Edition",
    "yearPublished": "1932",
    "isbn": "978-81-8461-182-1",
    "rate": 120,
    "bookType": "Digital PDF",
    "remarks1": "જેલમાં આપેલા અમર ગીતા પ્રવચનો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "83",
    "bookName": "ટોલ્સ્ટોય ની વાર્તાઓ",
    "author": "લિયો ટોલ્સ્ટોય (અનુ. મકરંદ દવે)",
    "translator": "મકરંદ દવે",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "વિશ્વ સાહિત્ય / બોધકથા",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1965",
    "isbn": "978-81-8461-183-8",
    "rate": 220,
    "bookType": "Digital PDF",
    "remarks1": "ટોલ્સ્ટોયની સત્ય અને નૈતિક વાર્તાઓ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "84",
    "bookName": "મારી જીવનકથા",
    "author": "નરસિંહરાવ દવેટિયા",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર સાહિત્ય ભવન",
    "category": "સંસ્મરણો / આત્મકથા",
    "language": "ગુજરાતી",
    "edition": "4th Edition",
    "yearPublished": "1938",
    "isbn": "978-81-8461-184-5",
    "rate": 260,
    "bookType": "Digital Epub",
    "remarks1": "પંડિત યુગના સર્જકની રસપ્રદ આત્મકથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "85",
    "bookName": "War Of Lanka",
    "author": "Amish Tripathi",
    "translator": "Original",
    "publisher": "HarperCollins Publishers",
    "category": "પૌરાણિક રોમાંચ",
    "language": "ઇંગ્લીશ",
    "edition": "1st Edition",
    "yearPublished": "2022",
    "isbn": "978-93-5629-570-4",
    "rate": 399,
    "bookType": "Digital PDF",
    "remarks1": "રામચંદ્ર સીરીઝનું રોમાંચક પુસ્તક",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "86",
    "bookName": "પૂર્વાલાપ",
    "author": "કવિ કાન્ત",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "કાવ્યસંગ્રહ / ખંડકાવ્યો",
    "language": "ગુજરાતી",
    "edition": "15th Edition",
    "yearPublished": "1923",
    "isbn": "978-81-8461-186-9",
    "rate": 180,
    "bookType": "Digital PDF",
    "remarks1": "ગુજરાતી સાહિત્યના અમર ખંડકાવ્યોનો સંગ્રહ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "87",
    "bookName": "કાવ્યમંગલા",
    "author": "સુંદરમ્",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "કાવ્યસંગ્રહ",
    "language": "ગુજરાતી",
    "edition": "12th Edition",
    "yearPublished": "1933",
    "isbn": "978-81-8461-187-6",
    "rate": 200,
    "bookType": "Digital PDF",
    "remarks1": "સુંદરમ્ નો સર્વપ્રસિદ્ધ કાવ્યસંગ્રહ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "88",
    "bookName": "વસુધા",
    "author": "સુંદરમ્",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "પ્રકૃતિ અને આધ્યાત્મિક કાવ્યો",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1939",
    "isbn": "978-81-8461-188-3",
    "rate": 210,
    "bookType": "Digital DOCX",
    "remarks1": "પ્રકૃતિપ્રેમ અને ચેતનાના સુંદર કાવ્યો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "89",
    "bookName": "યાત્રા",
    "author": "ઉમાશંકર જોશી",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "ઉત્તર ચિંતન કાવ્યો",
    "language": "ગુજરાતી",
    "edition": "8th Edition",
    "yearPublished": "1965",
    "isbn": "978-81-8461-189-0",
    "rate": 190,
    "bookType": "Digital Epub",
    "remarks1": "આધ્યાત્મિક અને દાર્શનિક સફરના કાવ્યો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "90",
    "bookName": "શ્રાવણી મેળો",
    "author": "ઉમાશંકર જોશી",
    "translator": "મૂળ",
    "publisher": "ગૂર્જર ગ્રંથરત્ન કાર્યાલય",
    "category": "ટૂંકી વાર્તાઓ",
    "language": "ગુજરાતી",
    "edition": "11th Edition",
    "yearPublished": "1937",
    "isbn": "978-81-8461-190-6",
    "rate": 180,
    "bookType": "Digital PDF",
    "remarks1": "ઉમાશંકર જોશીનો સુંદર વાર્તાસંગ્રહ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "91",
    "bookName": "ત્રિશંકુ",
    "author": "નિરંજન ભગત",
    "translator": "મૂળ",
    "publisher": "પ્રત્યક્ષ પ્રકાશન",
    "category": "આધુનિક કાવ્ય સાહિત્ય",
    "language": "ગુજરાતી",
    "edition": "6th Edition",
    "yearPublished": "1959",
    "isbn": "978-81-8461-191-3",
    "rate": 170,
    "bookType": "Digital PDF",
    "remarks1": "નગર કવિ નિરંજન ભગતની પ્રખ્યાત રચના",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "92",
    "bookName": "છંદોલય",
    "author": "નિરંજન ભગત",
    "translator": "મૂળ",
    "publisher": "પ્રત્યક્ષ પ્રકાશન",
    "category": "નગર કાવ્યો",
    "language": "ગુજરાતી",
    "edition": "9th Edition",
    "yearPublished": "1957",
    "isbn": "978-81-8461-192-0",
    "rate": 190,
    "bookType": "Digital PDF",
    "remarks1": "મુંબઈ નગરીના સંવેદનશીલ કાવ્યો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "93",
    "bookName": "અંગત",
    "author": "રાવજી પટેલ",
    "translator": "મૂળ",
    "publisher": "પ્રત્યક્ષ પ્રકાશન",
    "category": "સંવેદનશીલ કાવ્યસંગ્રહ",
    "language": "ગુજરાતી",
    "edition": "8th Edition",
    "yearPublished": "1971",
    "isbn": "978-81-8461-193-7",
    "rate": 180,
    "bookType": "Digital PDF",
    "remarks1": "રાવજી પટેલનો કરુણ અને અમર કાવ્યસંગ્રહ",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "94",
    "bookName": "ઝીલણ",
    "author": "હરીન્દ્ર દવે",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "ગીત અને ગઝલ સંગ્રહ",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1976",
    "isbn": "978-81-8461-194-4",
    "rate": 200,
    "bookType": "Digital Epub",
    "remarks1": "હરીન્દ્ર દવેના મધુર પ્રણય ગીતો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "95",
    "bookName": "અસૂર્યલોક",
    "author": "ભગવતીકુમાર શર્મા",
    "translator": "મૂળ",
    "publisher": "સાહિત્ય અકાદમી",
    "category": "સાહિત્ય અકાદમી વિજેતા નવલકથા",
    "language": "ગુજરાતી",
    "edition": "12th Edition",
    "yearPublished": "1987",
    "isbn": "978-81-8461-195-1",
    "rate": 280,
    "bookType": "Digital PDF",
    "remarks1": "અંધત્વ અને અસ્તિત્વની માર્મિક કથા",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "96",
    "bookName": "સોલ્ટ એન્ડ પેપર",
    "author": "વિનોદ ભટ્ટ",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "હાસ્ય અને કટાક્ષ",
    "language": "ગુજરાતી",
    "edition": "7th Edition",
    "yearPublished": "1981",
    "isbn": "978-81-8461-196-8",
    "rate": 210,
    "bookType": "Digital PDF",
    "remarks1": "વિનોદ ભટ્ટના અદ્ભુત હાસ્ય કટાક્ષ લેખો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "97",
    "bookName": "અમર કાવ્યો અને ગઝલો",
    "author": "મરીઝ",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "ગઝલ સંગ્રહ",
    "language": "ગુજરાતી",
    "edition": "14th Edition",
    "yearPublished": "1960",
    "isbn": "978-81-8461-197-5",
    "rate": 250,
    "bookType": "New Hard copy",
    "remarks1": "ગુજરાતના ગાલિબ મરીઝ સાહેબની ગઝલો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "98",
    "bookName": "સફર",
    "author": "મરીઝ",
    "translator": "મૂળ",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "category": "પ્રતિષ્ઠિત ગઝલ સંગ્રહ",
    "language": "ગુજરાતી",
    "edition": "10th Edition",
    "yearPublished": "1972",
    "isbn": "978-81-8461-198-2",
    "rate": 250,
    "bookType": "Digital PDF",
    "remarks1": "જીવન સંવેદનાની અજોડ શાયરી",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "99",
    "bookName": "સ્મરણ રેખા",
    "author": "સ્નેહરશ્મિ",
    "translator": "મૂળ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "હાઈકુ અને કાવ્યો",
    "language": "ગુજરાતી",
    "edition": "8th Edition",
    "yearPublished": "1968",
    "isbn": "978-81-8461-199-9",
    "rate": 190,
    "bookType": "Digital PDF",
    "remarks1": "જાપાની હાઈકુ શૈલીમાં રચેલા કાવ્યો",
    "addedDate": "2026-07-29"
  },
  {
    "bookId": "100",
    "bookName": "પૃથ્વી વલ્લભ",
    "author": "કનૈયાલાલ મુનશી",
    "translator": "મૂળ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની",
    "category": "ઐતિહાસિક નવલકથા",
    "language": "ગુજરાતી",
    "edition": "25th Edition",
    "yearPublished": "1920",
    "isbn": "978-81-8461-200-2",
    "rate": 280,
    "bookType": "Digital PDF",
    "remarks1": "મુંજ અને મૃણાલવતીની અમર ઐતિહાસિક કથા",
    "addedDate": "2026-07-29"
  }
];

// Map imported books to ensure exact Entry By mapping:
// Sr No 01 to 17 = Devdutt Thaker
// Sr No 18 to 107 = Jignesh Upadhyay
// Sr No 108 to 163 = Devdutt Thaker
export const IMPORTED_BOOKS: Book[] = RAW_IMPORTED_BOOKS.map((b) => {
  const num = parseInt(String(b.bookId || '').replace(/\D/g, ''), 10);
  const createdBy = (num >= 18 && num <= 107) ? 'Jignesh Upadhyay' : 'Devdutt Thaker';
  return { ...b, createdBy };
});

export const EXTRACTED_MASTERS: MasterData = {
  authors: [],
  categories: [],
  translators: [],
  languages: [],
  publishers: [],
  bookTypes: []
};
