import { Book, MasterData } from "./types";

export const IMPORTED_BOOKS: Book[] = [
  {
    "createdBy": "Devdutt Thaker",
    "language": "ગુજરાતી",
    "bookId": "1",
    "remarks1": "",
    "addedDate": "2026-07-29",
    "rate": 0,
    "translator": "",
    "isbn": "",
    "isIssued": true,
    "category": "ઈતિહાસ",
    "yearPublished": "",
    "bookName": "સૌરાષ્ટ્ર ની રસધાર - 01",
    "author": "ઝવેરચંદ મેઘાણી",
    "edition": "1",
    "currentIssueDueDate": "15-08-2026",
    "bookType": "New Paper Cover",
    "publisher": "",
    "currentBorrowerName": "DHAIVAT TRIVEDI"
  },
  {
    "publisher": "",
    "currentIssueDueDate": "29-10-2026",
    "author": "ઝવેરચંદ મેઘાણી",
    "bookType": "New Paper Cover",
    "currentBorrowerName": "DHAIVAT TRIVEDI",
    "edition": "1",
    "bookName": "સૌરાષ્ટ્ર ની રસધાર - 02",
    "isIssued": true,
    "rate": 0,
    "category": "ઈતિહાસ",
    "addedDate": "2026-07-29",
    "isbn": "",
    "yearPublished": "",
    "remarks1": "",
    "createdBy": "Devdutt Thaker",
    "bookId": "2",
    "language": "ગુજરાતી",
    "translator": ""
  },
  {
    "isIssued": true,
    "bookId": "3",
    "category": "ઈતિહાસ",
    "bookName": "સૌરાષ્ટ્ર ની રસધાર - 03",
    "publisher": "",
    "bookType": "New Paper Cover",
    "rate": 0,
    "isbn": "",
    "language": "ગુજરાતી",
    "currentBorrowerName": "NIRAV PANCHAL",
    "createdBy": "Devdutt Thaker",
    "remarks1": "",
    "yearPublished": "",
    "currentIssueDueDate": "29-10-2026",
    "addedDate": "2026-07-29",
    "translator": "",
    "edition": "1",
    "author": "ઝવેરચંદ મેઘાણી"
  },
  {
    "translator": "",
    "currentIssueDueDate": "15-08-2026",
    "rate": 100,
    "bookType": "New Paper Cover",
    "createdBy": "Devdutt Thaker",
    "currentBorrowerName": "Rudra Pathak",
    "author": "ઝવેરચંદ મેઘાણી",
    "isIssued": true,
    "category": "ઈતિહાસ",
    "bookName": "સૌરાષ્ટ્ર ની રસધાર - 04",
    "yearPublished": "2026",
    "bookId": "4",
    "language": "ગુજરાતી",
    "edition": "",
    "remarks1": "",
    "publisher": "શબ્દલોક પ્રકાશન",
    "isbn": ""
  },
  {
    "edition": "",
    "publisher": "શબ્દલોક પ્રકાશન",
    "yearPublished": "2026",
    "bookId": "5",
    "isbn": "",
    "remarks1": "",
    "language": "ગુજરાતી",
    "bookType": "New Paper Cover",
    "rate": 100,
    "bookName": "સૌરાષ્ટ્ર ની રસધાર - 05",
    "createdBy": "Devdutt Thaker",
    "translator": "",
    "category": "ઈતિહાસ",
    "author": "ઝવેરચંદ મેઘાણી"
  },
  {
    "remarks1": "કનૈયાલાલ મુનશીની ચૌલુક્ય યુગ નવલકથા શ્રેણીમાં આ ચાર નવલકથાઓનો વાંચવાનો ક્રમ આ મુજબ છે:  પાટણની પ્રભુતા, ગુજરાતનો નાથ, રાજાધિરાજ અને જય સોમનાથ",
    "createdBy": "Devdutt Thaker",
    "language": "ગુજરાતી",
    "author": "કનૈયાલાલ મુનશી",
    "rate": 300,
    "isbn": "",
    "bookName": "પાટણ ની પ્રભુતા",
    "edition": "",
    "bookId": "6",
    "category": "નવલકથા",
    "translator": "",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "yearPublished": "1939",
    "bookType": "New Hard Cover"
  },
  {
    "rate": 500,
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "bookType": "New Hard Cover",
    "author": "કનૈયાલાલ મુનશી",
    "bookName": "ગુજરાતનો નાથ",
    "category": "નવલકથા",
    "bookId": "7",
    "edition": "",
    "yearPublished": "1919",
    "remarks1": "કનૈયાલાલ મુનશીની ચૌલુક્ય યુગ નવલકથા શ્રેણીમાં આ ચાર નવલકથાઓનો વાંચવાનો ક્રમ આ મુજબ છે:  પાટણની પ્રભુતા, ગુજરાતનો નાથ, રાજાધિરાજ અને જય સોમનાથ",
    "isbn": "",
    "translator": "",
    "language": "ગુજરાતી",
    "createdBy": "Devdutt Thaker"
  },
  {
    "translator": "",
    "remarks1": "કનૈયાલાલ મુનશીની ચૌલુક્ય યુગ નવલકથા શ્રેણીમાં આ ચાર નવલકથાઓનો વાંચવાનો ક્રમ આ મુજબ છે:  પાટણની પ્રભુતા, ગુજરાતનો નાથ, રાજાધિરાજ અને જય સોમનાથ",
    "language": "ગુજરાતી",
    "isbn": "",
    "currentIssueDueDate": "02-11-2026",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "bookId": "8",
    "currentBorrowerName": "GHANSHYAM",
    "author": "કનૈયાલાલ મુનશી",
    "createdBy": "Devdutt Thaker",
    "bookName": "રાજાધીરાજ",
    "isIssued": true,
    "category": "નવલકથા",
    "edition": "",
    "yearPublished": "1939",
    "rate": 525,
    "bookType": "New Hard Cover"
  },
  {
    "category": "નવલકથા",
    "rate": 350,
    "author": "ઝવેરચંદ મેઘાણી",
    "bookName": "સોરઠી બહારવટિયા",
    "bookType": "New Hard Cover",
    "yearPublished": "2025",
    "translator": "",
    "edition": "",
    "createdBy": "Devdutt Thaker",
    "language": "ગુજરાતી",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "remarks1": "",
    "bookId": "9",
    "isbn": ""
  },
  {
    "remarks1": "",
    "language": "ગુજરાતી",
    "createdBy": "Devdutt Thaker",
    "yearPublished": "2024",
    "bookId": "10",
    "rate": 700,
    "translator": "",
    "author": "રજનીકુમાર પંડ્યા",
    "bookName": "ઝબકાર",
    "isbn": "",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "edition": "1",
    "bookType": "New Paper Cover",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની પ્રા. લિ."
  },
  {
    "currentBorrowerName": "HEET JAVIYA",
    "isbn": "",
    "yearPublished": "2025",
    "author": "ધ્રુવ ભટ્ટ",
    "translator": "",
    "bookType": "New Paper Cover",
    "currentIssueDueDate": "03-11-2026",
    "edition": "",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "bookName": "સમુદ્રાન્તિકે",
    "isIssued": true,
    "category": "નવલકથા",
    "createdBy": "Devdutt Thaker",
    "remarks1": "",
    "bookId": "11",
    "language": "ગુજરાતી",
    "rate": 200
  },
  {
    "isbn": "",
    "publisher": "સાર્થક પ્રકાશન",
    "edition": "1",
    "language": "ગુજરાતી",
    "translator": "",
    "remarks1": "",
    "author": "ધૈવત ત્રિવેદી",
    "bookType": "New Paper Cover",
    "bookId": "12",
    "rate": 250,
    "yearPublished": "2019",
    "category": "નવલકથા",
    "bookName": "મેક્લિન એસ્ટેટ",
    "createdBy": "Devdutt Thaker"
  },
  {
    "bookName": "વિસ્મય - 01",
    "bookId": "13",
    "category": "લેખ",
    "translator": "",
    "publisher": "સાર્થક પ્રકાશન",
    "rate": 0,
    "bookType": "New Paper Cover",
    "yearPublished": "",
    "remarks1": "",
    "edition": "1",
    "createdBy": "Devdutt Thaker",
    "isbn": "",
    "language": "ગુજરાતી",
    "author": "ધૈવત ત્રિવેદી"
  },
  {
    "rate": 0,
    "bookId": "14",
    "bookName": "વિસ્મય - 02",
    "edition": "1",
    "category": "લેખ",
    "createdBy": "Devdutt Thaker",
    "bookType": "New Paper Cover",
    "remarks1": "",
    "yearPublished": "",
    "language": "ગુજરાતી",
    "publisher": "સાર્થક પ્રકાશન",
    "author": "ધૈવત ત્રિવેદી",
    "translator": "",
    "isbn": ""
  },
  {
    "language": "ગુજરાતી",
    "rate": 0,
    "author": "ધૈવત ત્રિવેદી",
    "translator": "",
    "remarks1": "",
    "publisher": "સાર્થક પ્રકાશન",
    "edition": "1",
    "category": "લેખ",
    "createdBy": "Devdutt Thaker",
    "bookName": "વિસ્મય - 03",
    "bookType": "New Paper Cover",
    "bookId": "15",
    "yearPublished": "",
    "isbn": ""
  },
  {
    "edition": "1",
    "publisher": "સાર્થક પ્રકાશન",
    "yearPublished": "",
    "bookId": "16",
    "isbn": "",
    "remarks1": "",
    "language": "ગુજરાતી",
    "bookType": "New Paper Cover",
    "rate": 0,
    "createdBy": "Devdutt Thaker",
    "bookName": "વિસ્મય - 04",
    "translator": "",
    "author": "ધૈવત ત્રિવેદી",
    "category": "લેખ"
  },
  {
    "language": "ગુજરાતી",
    "translator": "",
    "author": "ધૈવત ત્રિવેદી",
    "yearPublished": "",
    "remarks1": "",
    "rate": 0,
    "publisher": "સાર્થક પ્રકાશન",
    "createdBy": "Devdutt Thaker",
    "category": "લેખ",
    "isbn": "",
    "bookName": "વિસ્મય - 05",
    "bookType": "New Paper Cover",
    "bookId": "17",
    "edition": "1"
  },
  {
    "createdBy": "Jignesh Upadhyay",
    "bookId": "18",
    "rate": 350,
    "yearPublished": "1",
    "translator": "",
    "language": "ગુજરાતી",
    "remarks1": "",
    "bookType": "New Paper Cover",
    "author": "ફાધર વાલેસ",
    "edition": "2025",
    "isbn": "",
    "category": "સંપાદન",
    "publisher": "ZEN OPUS",
    "bookName": "e લીગન્સ"
  },
  {
    "author": "પન્ના નાયક",
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "",
    "language": "ગુજરાતી",
    "edition": "2025",
    "translator": "",
    "isbn": "",
    "yearPublished": "JAN",
    "bookName": "e મરલ્ડ",
    "rate": 350,
    "category": "સંપાદન",
    "publisher": "ZEN OPUS",
    "bookId": "19",
    "bookType": "New Paper Cover"
  },
  {
    "publisher": "રમેશ તન્ના",
    "author": "01.  સંકલિત",
    "bookType": "New Paper Cover",
    "edition": "2024",
    "bookName": "માતૃભાષા મોરી મોરી રે",
    "rate": 325,
    "category": "સંપાદન",
    "isbn": "",
    "yearPublished": "feb",
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "જુદા જુદા ક્ષેત્રની વ્યક્તિઓએ માતૃભાષા ગુજરાતી વિષે વ્યક્ત કરેલા હ્રદયભાવનો સંચય",
    "bookId": "20",
    "translator": "",
    "language": "ગુજરાતી"
  },
  {
    "language": "ગુજરાતી",
    "remarks1": "સંવર્ધિત આવૃત્તિ",
    "edition": "2026",
    "author": "વિજયગુપ્ત મોર્ય",
    "isbn": "",
    "createdBy": "Jignesh Upadhyay",
    "category": "ઈતિહાસ",
    "rate": 450,
    "bookName": "કાશ્મીરનું અગ્નિસ્નાન",
    "bookId": "21",
    "yearPublished": "7",
    "publisher": "હર્ષલ પબ્લિકેશન",
    "bookType": "New Hard Cover",
    "translator": ""
  },
  {
    "createdBy": "Jignesh Upadhyay",
    "category": "ધાર્મિક / આધ્યાત્મિક",
    "translator": "",
    "author": "01.  સંકલિત",
    "bookName": "SILVER JUBILEE SOUVENIR - 2023",
    "bookType": "New Paper Cover",
    "rate": 50,
    "yearPublished": "1",
    "language": "ઈંગ્લીશ",
    "isbn": "",
    "remarks1": "RAMKRISHNA MISSION VIVEKANAND MOMERIAL",
    "publisher": "SWAMI ATMADIPANANDA",
    "edition": "2023",
    "bookId": "22"
  },
  {
    "translator": "",
    "yearPublished": "2",
    "createdBy": "Jignesh Upadhyay",
    "rate": 100,
    "language": "ગુજરાતી",
    "bookId": "23",
    "remarks1": "",
    "bookType": "New Paper Cover",
    "author": "કિશોર મકવાણા",
    "isbn": "",
    "category": "સંપાદન",
    "publisher": "મેઘનિર્ઘોષ મીડિયા પ્રા. લી.",
    "edition": "2023",
    "bookName": "મૃત્યુંજયી સાવરકર"
  },
  {
    "bookType": "New Paper Cover",
    "author": "આર. એમ. લાલા",
    "category": "અન્ય",
    "createdBy": "Jignesh Upadhyay",
    "bookName": "સંપત્તિનું સર્જન",
    "isbn": "",
    "bookId": "24",
    "rate": 195,
    "translator": "ભોળાભાઈ પટેલ",
    "yearPublished": "6",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની પ્રા. લિ.",
    "language": "ગુજરાતી",
    "edition": "2010",
    "remarks1": "૧૯મી થી ૨૧મી સદી સુધીની ટાટા પેઢીની કથા"
  },
  {
    "author": "લાલભાઈ ઉત્તમરામ  ત્રિવેદી",
    "remarks1": "આત્મકથન",
    "language": "ગુજરાતી",
    "rate": 0,
    "edition": "2002",
    "publisher": "લાલભાઈ ઉત્તમરામ ત્રિવેદી",
    "createdBy": "Jignesh Upadhyay",
    "bookName": "જીવનયાત્રા - કેટલાક સંભારણા",
    "translator": "",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "isbn": "",
    "bookId": "25",
    "bookType": "New Hard Cover",
    "yearPublished": "5"
  },
  {
    "rate": 180,
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "",
    "author": "નગેન્દ્ર વિજય",
    "yearPublished": "",
    "language": "ગુજરાતી",
    "bookId": "26",
    "edition": "",
    "bookType": "New Paper Cover",
    "translator": "",
    "isbn": "",
    "bookName": "આઈનસ્ટાઇન અને સાપેક્ષવાદ",
    "publisher": "યુરેનસ બુક્સ",
    "category": "કમ્પ્યુટર / ટેકનોલોજી / વિજ્ઞાન"
  },
  {
    "remarks1": "ગુજરાત કેડરના અગિયાર ઓજસવી અધિકારીઓની અત્યંત અદભૂત અને સફળ કહાણીઓ",
    "createdBy": "Jignesh Upadhyay",
    "author": "લાભુ દેસાઇ",
    "language": "ગુજરાતી",
    "yearPublished": "",
    "rate": 249,
    "isbn": "",
    "bookName": "ધાર્યું તે કર્યું",
    "category": "સંપાદન",
    "edition": "2023",
    "publisher": "વિદ્યાભારતી સાહિત્ય સંસ્થા",
    "translator": "",
    "bookId": "27",
    "bookType": "New Paper Cover"
  },
  {
    "publisher": "એમ. એમ સાહિત્ય પ્રકાશન",
    "translator": "",
    "bookName": "બાળવાર્તાઓ",
    "category": "વાર્તા / વાર્તાઓ",
    "rate": 35,
    "bookId": "28",
    "yearPublished": "",
    "bookType": "New Paper Cover",
    "remarks1": "બાળ સાહિત્યકાર ઉમિયાશંકર લિખિત",
    "author": "જગદીશ ઉ ઠાકર",
    "language": "ગુજરાતી",
    "isbn": "",
    "edition": "2013",
    "createdBy": "Jignesh Upadhyay"
  },
  {
    "edition": "",
    "yearPublished": "",
    "remarks1": "",
    "createdBy": "Jignesh Upadhyay",
    "translator": "",
    "rate": 500,
    "language": "ગુજરાતી",
    "author": "મનસુખભાઇ સુવાગીયા",
    "publisher": "જળક્રાંતિ ટ્રસ્ટ",
    "isbn": "",
    "bookType": "New Hard Cover",
    "bookId": "29",
    "bookName": "ગોવેદ",
    "category": "લેખ"
  },
  {
    "language": "ગુજરાતી",
    "translator": "",
    "remarks1": "",
    "bookId": "30",
    "publisher": "print box",
    "yearPublished": "",
    "isbn": "",
    "edition": "2014",
    "createdBy": "Jignesh Upadhyay",
    "author": "01.  સંકલિત",
    "category": "લેખ",
    "rate": 275,
    "bookName": "વિજ્ઞાન અને ટેકનોલોજી જ્ઞાનકોષ",
    "bookType": "New Hard Cover"
  },
  {
    "yearPublished": "",
    "translator": "",
    "bookType": "New Paper Cover",
    "author": "નગેન્દ્ર વિજય",
    "isbn": "",
    "bookName": "વિશ્વવિગ્રહની યાદગાર યુદ્ધકથાઓ - ભાગ 1",
    "publisher": "મૌર્ય મીડિયા",
    "category": "ઈતિહાસ",
    "edition": "",
    "rate": 150,
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "પ્રથમ અને બીજા વિશ્વયુદ્ધ દરમ્યાન ખેલાયેલા અપ્રતિમ સાહસો",
    "language": "ગુજરાતી",
    "bookId": "31"
  },
  {
    "rate": 150,
    "language": "ગુજરાતી",
    "createdBy": "Jignesh Upadhyay",
    "bookId": "32",
    "remarks1": "પ્રથમ અને બીજા વિશ્વયુદ્ધ દરમ્યાન ખેલાયેલા અપ્રતિમ સાહસો",
    "bookType": "New Paper Cover",
    "yearPublished": "",
    "author": "નગેન્દ્ર વિજય",
    "publisher": "મૌર્ય મીડિયા",
    "category": "ઈતિહાસ",
    "isbn": "",
    "translator": "",
    "edition": "",
    "bookName": "વિશ્વવિગ્રહની યાદગાર યુદ્ધકથાઓ - ભાગ 2"
  },
  {
    "bookType": "New Paper Cover",
    "yearPublished": "",
    "author": "નગેન્દ્ર વિજય",
    "category": "ઈતિહાસ",
    "createdBy": "Jignesh Upadhyay",
    "bookName": "વિશ્વવિગ્રહની યાદગાર યુદ્ધકથાઓ - ભાગ 3",
    "isbn": "",
    "bookId": "33",
    "rate": 150,
    "publisher": "મૌર્ય મીડિયા",
    "translator": "",
    "language": "ગુજરાતી",
    "edition": "",
    "remarks1": "પ્રથમ અને બીજા વિશ્વયુદ્ધ દરમ્યાન ખેલાયેલા અપ્રતિમ સાહસો"
  },
  {
    "rate": 350,
    "language": "ગુજરાતી",
    "author": "વિજયગુપ્ત મોર્ય",
    "remarks1": "નરમાંસ આરોગીને મોત સામે જજુમેલા બહાદુરોની દિલધડક સત્યકથા",
    "createdBy": "Jignesh Upadhyay",
    "edition": "2026",
    "category": "સત્યઘટના",
    "yearPublished": "5",
    "publisher": "હર્ષલ પબ્લિકેશન",
    "bookName": "જિંદગી જિંદગી",
    "bookType": "New Hard Cover",
    "bookId": "34",
    "translator": "નગેન્દ્ર વિજય",
    "isbn": ""
  },
  {
    "bookType": "New Hard Cover",
    "publisher": "હર્ષલ પબ્લિકેશન",
    "yearPublished": "2",
    "bookId": "35",
    "category": "કમ્પ્યુટર / ટેકનોલોજી / વિજ્ઞાન",
    "isbn": "",
    "translator": "",
    "bookName": "વિજ્ઞાનની વાર્તાઓ",
    "author": "નગેન્દ્ર વિજય",
    "rate": 500,
    "createdBy": "Jignesh Upadhyay",
    "language": "ગુજરાતી",
    "edition": "2025",
    "remarks1": ""
  },
  {
    "isbn": "",
    "bookId": "36",
    "createdBy": "Jignesh Upadhyay",
    "edition": "2011",
    "language": "ગુજરાતી",
    "remarks1": "",
    "bookType": "New Paper Cover",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "પ્રવાસ",
    "yearPublished": "3",
    "rate": 100,
    "bookName": "રખડવાનો આનંદ",
    "translator": "",
    "author": "કાકાસાહેબ કાલેલકર"
  },
  {
    "isbn": "",
    "yearPublished": "4",
    "translator": "",
    "author": "ડૉ. પન્ના ત્રિવેદી",
    "language": "ગુજરાતી",
    "createdBy": "Jignesh Upadhyay",
    "edition": "2023",
    "remarks1": "",
    "bookType": "New Paper Cover",
    "publisher": "ગુર્જર સાહિત્ય પ્રકાશન",
    "category": "લેખ",
    "rate": 350,
    "bookId": "37",
    "bookName": "પરિષ્કૃત"
  },
  {
    "isbn": "",
    "yearPublished": "4",
    "edition": "2026",
    "createdBy": "Jignesh Upadhyay",
    "translator": "હરદ્વાર ગોસ્વામી",
    "remarks1": "",
    "language": "ગુજરાતી",
    "author": "01.  સંકલિત",
    "bookType": "New Paper Cover",
    "bookId": "38",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "bookName": "એવરગ્રીન ગુજરાતી",
    "category": "કવિતા",
    "rate": 249
  },
  {
    "category": "લેખ",
    "bookId": "39",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "isbn": "",
    "bookName": "અસ્તિત્વનો ઉઘાડ",
    "yearPublished": "12",
    "bookType": "New Paper Cover",
    "language": "ગુજરાતી",
    "remarks1": "પળેપલ પમરતો હોવાનો હરખ",
    "translator": "",
    "createdBy": "Jignesh Upadhyay",
    "author": "હરદ્વાર ગોસ્વામી",
    "edition": "2024",
    "rate": 250
  },
  {
    "category": "લેખ",
    "bookName": "તાઓ ઝેન કન્ફ્યુશિયસ",
    "createdBy": "Jignesh Upadhyay",
    "bookType": "New Hard Cover",
    "translator": "",
    "bookId": "40",
    "rate": 150,
    "isbn": "",
    "language": "ગુજરાતી",
    "publisher": "ડીવાઈન પબ્લિકેશન",
    "author": "ડૉ. પ્રદીપ પંડયા",
    "remarks1": "",
    "yearPublished": "7",
    "edition": "2008"
  },
  {
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "author": "કલ્પેશ અખાણી",
    "bookType": "New Paper Cover",
    "edition": "2008",
    "bookName": "ગણિત વિનોદ",
    "rate": 30,
    "category": "ભાષા / ભણતર / એજ્યુકેશન /",
    "isbn": "",
    "yearPublished": "3",
    "remarks1": "",
    "createdBy": "Jignesh Upadhyay",
    "bookId": "41",
    "language": "ગુજરાતી",
    "translator": ""
  },
  {
    "language": "ગુજરાતી",
    "yearPublished": "12",
    "remarks1": "વર્સેટાઈલ વુમનનો નોખો નભોવિહાર",
    "translator": "",
    "isbn": "",
    "createdBy": "Jignesh Upadhyay",
    "edition": "2024",
    "bookId": "42",
    "category": "પોઝેટીવ એટીટ્યુડ",
    "rate": 325,
    "author": "રક્ષા શુક્લ",
    "bookName": "કાર્યેષુ મંત્રી",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "bookType": "New Paper Cover"
  },
  {
    "author": "લલીત ખંભાયતા",
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "અખબારી પાનાઓ પર પ્રગટ થયેલો ગુજરાતી સાહિત્યનો વૈભવ",
    "language": "ગુજરાતી",
    "edition": "2025",
    "translator": "",
    "isbn": "",
    "yearPublished": "10",
    "bookName": "ઉતાવળે સર્જાયેલું સાહિત્ય",
    "rate": 349,
    "category": "લેખ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "bookId": "43",
    "bookType": "New Paper Cover"
  },
  {
    "createdBy": "Jignesh Upadhyay",
    "bookId": "44",
    "rate": 9,
    "yearPublished": "",
    "translator": "સ્મિતા શાહ",
    "language": "ગુજરાતી",
    "remarks1": "",
    "bookType": "New Paper Cover",
    "author": "લઈક ફતેહઅલી",
    "isbn": "",
    "edition": "",
    "publisher": "નેશનલ બુક ટ્રસ્ટ ઈન્ડિયા",
    "category": "ભાષા / ભણતર / એજ્યુકેશન /",
    "bookName": "આપણી પૃથ્વી"
  },
  {
    "language": "ગુજરાતી",
    "translator": "",
    "author": "ડૉ. રવજી ગાબાની",
    "yearPublished": "11",
    "remarks1": "માણસને માણસ બનવા પ્રેરિત કરતી કેટલીક સંવેદનકથાઓ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "rate": 500,
    "createdBy": "Jignesh Upadhyay",
    "category": "લેખ",
    "isbn": "",
    "bookName": "જિંદગીના સ્ક્રીનશોટ - હ્રદયના ભોંય ભીની કરતી વાતો",
    "bookType": "New Paper Cover",
    "bookId": "45",
    "edition": "2025"
  },
  {
    "isbn": "",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "edition": "2017",
    "language": "ગુજરાતી",
    "remarks1": "વિદ્યાર્થીઓને પરીક્ષા માટે તૈયાર કરતું સંપૂર્ણ પુસ્તક",
    "author": "ડૉ. નિમિત્ત ઓઝા",
    "bookType": "New Paper Cover",
    "yearPublished": "10",
    "bookId": "46",
    "category": "પોઝેટીવ એટીટ્યુડ",
    "rate": 185,
    "bookName": "મારી વહાલી પરીક્ષા",
    "createdBy": "Jignesh Upadhyay",
    "translator": ""
  },
  {
    "bookId": "47",
    "bookName": "ભગવાનનું માણહ",
    "createdBy": "Jignesh Upadhyay",
    "edition": "2026",
    "category": "સંપાદન",
    "isbn": "",
    "bookType": "New Paper Cover",
    "remarks1": "21મી સદીના ઉત્કૃષ્ટ રેખાચિત્રો",
    "rate": 399,
    "translator": "",
    "language": "ગુજરાતી",
    "author": "પન્ના ત્રિવેદી",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "yearPublished": "4"
  },
  {
    "language": "ગુજરાતી",
    "bookId": "48",
    "remarks1": "એક શિક્ષકના વિદ્યાર્થીઓ સાથેના સંવેદનશીલ પ્રસંગો",
    "createdBy": "Jignesh Upadhyay",
    "rate": 150,
    "isbn": "",
    "category": "લેખ",
    "bookName": "શિક્ષણમાંથી શિક્ષણ",
    "yearPublished": "1",
    "author": "પરેશ ત્રિવેદી",
    "edition": "2026",
    "bookType": "New Paper Cover",
    "translator": "",
    "publisher": "પરેશ ત્રિવેદી"
  },
  {
    "language": "ગુજરાતી",
    "author": "લલીત ખંભાયતા",
    "rate": 350,
    "remarks1": "સદાકાળ સથવારો આપતી સત્યકથાઓ",
    "createdBy": "Jignesh Upadhyay",
    "edition": "2026",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "સત્યઘટના",
    "bookName": "બ્રેવહાર્ટ્સ - 1",
    "bookId": "49",
    "yearPublished": "1",
    "bookType": "New Hard Cover",
    "translator": "",
    "isbn": ""
  },
  {
    "rate": 399,
    "bookId": "50",
    "bookType": "New Paper Cover",
    "bookName": "વાણિજ્ય વિમર્શ",
    "yearPublished": "9",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "category": "લેખ",
    "edition": "2025",
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "દેશવિદેશના અર્થતંત્રના જટિલ પ્રશ્નો વિશેના લેખો",
    "translator": "",
    "author": "ડૉ. જયનારાયણ વ્યાસ",
    "isbn": "",
    "language": "ગુજરાતી"
  },
  {
    "translator": "",
    "yearPublished": "1",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "author": "ડૉ. ભરત ભગત",
    "isbn": "",
    "remarks1": "પરમાર્થ-પ્રેરક સંસ્થાઓ અને વ્યક્તિઓનું અભિવાદન",
    "language": "ગુજરાતી",
    "rate": 200,
    "edition": "2025",
    "bookType": "New Hard Cover",
    "bookName": "પરમાર્થના મેઘધનુષ",
    "category": "પોઝેટીવ એટીટ્યુડ",
    "bookId": "51",
    "createdBy": "Jignesh Upadhyay"
  },
  {
    "createdBy": "Jignesh Upadhyay",
    "language": "ગુજરાતી",
    "rate": 120,
    "remarks1": "",
    "bookId": "52",
    "edition": "2026",
    "category": "વાર્તા / વાર્તાઓ",
    "author": "બીના ગાંધી કાનાણી",
    "yearPublished": "1",
    "bookName": "વુમન નેક્સ્ટ ડોર",
    "isbn": "",
    "bookType": "New Paper Cover",
    "translator": "",
    "publisher": "બીના કાનાણી"
  },
  {
    "isbn": "",
    "bookType": "Old Paper Cover",
    "yearPublished": "",
    "category": "લેખ",
    "edition": "",
    "createdBy": "Jignesh Upadhyay",
    "bookName": "મનનું પુસ્તકપટ",
    "bookId": "53",
    "publisher": "હરિ ઓફસેટ",
    "author": "જાગૃતિ રસીકલાલ વકીલ",
    "language": "ગુજરાતી",
    "translator": "",
    "rate": 0,
    "remarks1": "વાંચેલા પુસ્તકોના જિલેલા અણસારો"
  },
  {
    "createdBy": "Jignesh Upadhyay",
    "bookId": "54",
    "language": "ઈંગ્લીશ",
    "rate": 199,
    "remarks1": "",
    "yearPublished": "1",
    "edition": "2025",
    "translator": "",
    "category": "લેખ",
    "bookName": "THE SEASON OF AASHI",
    "author": "CHANDANI GOSWAMI",
    "isbn": "",
    "bookType": "New Paper Cover",
    "publisher": "ForEVER SHINNING"
  },
  {
    "category": "પોઝેટીવ એટીટ્યુડ",
    "yearPublished": "16",
    "bookName": "સફળતાનું રહસ્ય",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "bookType": "Old Paper Cover",
    "rate": 40,
    "publisher": "શ્રીકૃષ્ણ આશ્રમ",
    "language": "ગુજરાતી",
    "createdBy": "Jignesh Upadhyay",
    "isbn": "",
    "remarks1": "સર્વાંગી વ્યક્તિત્વ વિકાસ",
    "translator": "",
    "edition": "2022",
    "bookId": "55"
  },
  {
    "category": "લેખ",
    "yearPublished": "1",
    "author": "રાજ ભાસ્કર",
    "bookName": "લવ યુ દોસ્ત",
    "bookType": "New Paper Cover",
    "rate": 400,
    "publisher": "બૂકશેલ્ફ",
    "language": "ગુજરાતી",
    "createdBy": "Jignesh Upadhyay",
    "isbn": "",
    "remarks1": "લેખકો અને પત્રકારો તથા વિવિધ ક્ષેત્રના વ્યક્તિઓએ મિત્ર વિષે લખેલા લેખોનો સંચય",
    "translator": "",
    "edition": "2017",
    "bookId": "56"
  },
  {
    "edition": "",
    "translator": "",
    "remarks1": "ફોટોવિજન",
    "publisher": "ફોટોવીજન એકેડમી",
    "rate": 350,
    "language": "ગુજરાતી",
    "author": "શૈલેષ રાવલ",
    "bookName": "સંજય  દ્રષ્ટિ",
    "bookId": "57",
    "category": "લેખ",
    "createdBy": "Jignesh Upadhyay",
    "yearPublished": "",
    "isbn": "",
    "bookType": "New Hard Cover"
  },
  {
    "language": "ગુજરાતી",
    "rate": 75,
    "author": "રમેશ પુરોહિત",
    "translator": "",
    "remarks1": "",
    "publisher": "Image Publication",
    "edition": "1992",
    "category": "સંપાદન",
    "createdBy": "Jignesh Upadhyay",
    "bookName": "ગઝલ ૧૦૧",
    "bookType": "New Paper Cover",
    "bookId": "58",
    "yearPublished": "1",
    "isbn": ""
  },
  {
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "isbn": "",
    "bookName": "અગ્નિકુંડમાં ઊગેલું ગુલાબ",
    "createdBy": "Jignesh Upadhyay",
    "bookType": "New Hard Cover",
    "author": "નારાયણ દેસાઈ",
    "language": "ગુજરાતી",
    "remarks1": "મહાદેવભાઈનું જીવનચરિત્ર",
    "bookId": "59",
    "edition": "1992",
    "rate": 50,
    "translator": "",
    "publisher": "અમૃત મોદી",
    "yearPublished": "10"
  },
  {
    "translator": "",
    "isbn": "",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "bookType": "New Paper Cover",
    "edition": "2014",
    "bookName": "ગુજરાતમાં સ્વામી વિવેકાનંદ",
    "category": "ધાર્મિક / આધ્યાત્મિક",
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "",
    "bookId": "60",
    "language": "ગુજરાતી",
    "yearPublished": "1",
    "rate": 0
  },
  {
    "yearPublished": "2",
    "translator": "",
    "bookType": "Old Paper Cover",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "isbn": "",
    "bookName": "સબંધોનું મેનેજમેન્ટ",
    "category": "ધાર્મિક / આધ્યાત્મિક",
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "edition": "2023",
    "createdBy": "Jignesh Upadhyay",
    "rate": 0,
    "remarks1": "",
    "bookId": "61",
    "language": "ગુજરાતી"
  },
  {
    "translator": "",
    "yearPublished": "12",
    "bookName": "શ્રીરામકૃષ્ણ આરાત્રિકમ",
    "isbn": "",
    "category": "ધાર્મિક / આધ્યાત્મિક",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "createdBy": "Jignesh Upadhyay",
    "bookType": "Old Paper Cover",
    "remarks1": "",
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "bookId": "62",
    "edition": "2024",
    "language": "ગુજરાતી",
    "rate": 0
  },
  {
    "language": "ગુજરાતી",
    "remarks1": "",
    "bookId": "63",
    "yearPublished": "6",
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "rate": 0,
    "isbn": "",
    "category": "પોઝેટીવ એટીટ્યુડ",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "createdBy": "Jignesh Upadhyay",
    "bookName": "ટાઈમ મેનેજમેન્ટ",
    "bookType": "Old Paper Cover",
    "translator": "",
    "edition": "2024"
  },
  {
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "category": "પોઝેટીવ એટીટ્યુડ",
    "bookName": "શિક્ષક તો છે જ્યોતિર્ધર",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "edition": "2021",
    "bookType": "Old Paper Cover",
    "translator": "",
    "isbn": "",
    "bookId": "64",
    "rate": 0,
    "language": "ગુજરાતી",
    "remarks1": "",
    "yearPublished": "9",
    "createdBy": "Jignesh Upadhyay"
  },
  {
    "edition": "2022",
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "bookType": "Old Paper Cover",
    "bookName": "પત્ર-પત્રિકાઓના પ્રવર્તક સ્વામી વિવેકાનંદ",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "rate": 0,
    "category": "પોઝેટીવ એટીટ્યુડ",
    "isbn": "",
    "bookId": "65",
    "yearPublished": "8",
    "remarks1": "",
    "translator": "",
    "language": "ગુજરાતી",
    "createdBy": "Jignesh Upadhyay"
  },
  {
    "bookId": "66",
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "bookName": "એન્જોયગ્રાફી",
    "edition": "2006",
    "category": "પોઝેટીવ એટીટ્યુડ",
    "translator": "",
    "isbn": "",
    "bookType": "Old Paper Cover",
    "remarks1": "",
    "rate": 50,
    "language": "ગુજરાતી",
    "author": "રતિલાલ બોરીસાગર",
    "yearPublished": "2",
    "createdBy": "Jignesh Upadhyay"
  },
  {
    "edition": "2022",
    "remarks1": "",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "rate": 0,
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "language": "ગુજરાતી",
    "isbn": "",
    "bookId": "67",
    "yearPublished": "6",
    "bookType": "New Paper Cover",
    "createdBy": "Jignesh Upadhyay",
    "bookName": "એકાગ્રતા અને ધ્યાન",
    "translator": "",
    "category": "પોઝેટીવ એટીટ્યુડ"
  },
  {
    "bookType": "New Paper Cover",
    "rate": 0,
    "author": "ડૉ. એ. પી. જે. અબ્દુલ કલામ",
    "createdBy": "Jignesh Upadhyay",
    "yearPublished": "9",
    "category": "પોઝેટીવ એટીટ્યુડ",
    "bookName": "સ્વામી વિવેકાનંદ અને ભારતના યુવાનો",
    "language": "ગુજરાતી",
    "translator": "",
    "bookId": "68",
    "edition": "2022",
    "isbn": "",
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "remarks1": ""
  },
  {
    "language": "ગુજરાતી",
    "remarks1": "",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "rate": 299,
    "author": "દિપક મેઘાણી",
    "yearPublished": "12",
    "category": "કવિતા",
    "bookName": "અગ્નિગંગા",
    "isbn": "",
    "bookId": "69",
    "translator": "",
    "edition": "2025",
    "bookType": "New Paper Cover",
    "createdBy": "Jignesh Upadhyay"
  },
  {
    "bookType": "New Paper Cover",
    "author": "સમીર દેખૈયા પત્રાવાળા",
    "bookName": "ફકીરની પાળ",
    "isbn": "",
    "category": "વાર્તા / વાર્તાઓ",
    "publisher": "ZEN OPUS",
    "edition": "2024",
    "rate": 225,
    "yearPublished": "7",
    "createdBy": "Jignesh Upadhyay",
    "translator": "",
    "remarks1": "૧૭ ટૂંકી વાર્તાઓનો સમૂહ",
    "bookId": "70",
    "language": "ગુજરાતી"
  },
  {
    "bookName": "વિશ્વવંદ્ય સ્વામી વિવેકાનંદ",
    "isbn": "",
    "category": "પોઝેટીવ એટીટ્યુડ",
    "createdBy": "Jignesh Upadhyay",
    "bookType": "Old Paper Cover",
    "bookId": "71",
    "remarks1": "",
    "language": "ગુજરાતી",
    "edition": "2022",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "rate": 0,
    "yearPublished": "8",
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "translator": ""
  },
  {
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "createdBy": "Jignesh Upadhyay",
    "yearPublished": "12",
    "remarks1": "",
    "isbn": "",
    "language": "ગુજરાતી",
    "rate": 0,
    "bookType": "Old Paper Cover",
    "edition": "2024",
    "bookId": "72",
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "bookName": "વિશ્વવંદ્ય શ્રી રામકૃષ્ણ દેવ",
    "translator": "",
    "category": "પોઝેટીવ એટીટ્યુડ"
  },
  {
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "translator": "",
    "language": "ગુજરાતી",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "remarks1": "",
    "isbn": "",
    "rate": 0,
    "bookType": "Old Paper Cover",
    "bookId": "73",
    "edition": "2024",
    "createdBy": "Jignesh Upadhyay",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "bookName": "વિશ્વજનની માં શારદાદેવી",
    "yearPublished": "12"
  },
  {
    "remarks1": "",
    "rate": 0,
    "edition": "2023",
    "language": "ગુજરાતી",
    "translator": "",
    "createdBy": "Jignesh Upadhyay",
    "bookId": "74",
    "publisher": "રામકૃષ્ણ આશ્રમ - રાજકોટ",
    "bookName": "આધુનિક માનવ અમૃતની શોધમાં",
    "author": "સ્વામી  નીખીલેશ્વરાનંદ",
    "category": "ધાર્મિક / આધ્યાત્મિક",
    "yearPublished": "1",
    "bookType": "New Paper Cover",
    "isbn": ""
  },
  {
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "remarks1": "સમાજ માટે સમર્પિત સંસ્થાઓ અને વ્યક્તિઓની બિરદાવલિ",
    "language": "ગુજરાતી",
    "translator": "",
    "rate": 200,
    "bookId": "75",
    "yearPublished": "1",
    "author": "ડૉ. ભરત ભગત",
    "bookName": "સેવાધર્મ તો એને રે કહીએ..",
    "category": "પોઝેટીવ એટીટ્યુડ",
    "isbn": "",
    "edition": "2025",
    "createdBy": "Jignesh Upadhyay",
    "bookType": "New Paper Cover"
  },
  {
    "rate": 0,
    "publisher": "quickprint publishing",
    "author": "સુનિલ અંજારિયા",
    "yearPublished": "",
    "language": "ગુજરાતી",
    "remarks1": "",
    "bookId": "76",
    "bookType": "New Paper Cover",
    "edition": "2026",
    "category": "લેખ",
    "isbn": "",
    "translator": "",
    "bookName": "આસપાસની ખાસ વાતો",
    "createdBy": "Jignesh Upadhyay"
  },
  {
    "bookType": "New Hard Cover",
    "isbn": "",
    "createdBy": "Jignesh Upadhyay",
    "category": "લેખ",
    "translator": "",
    "edition": "2026",
    "bookName": "શિક્ષાપત્રી - ટાઈમલેસ મેનેજમેન્ટ વિજડમ",
    "bookId": "77",
    "author": "ડૉ. મનીષ ચાવડા",
    "language": "ગુજરાતી",
    "rate": 499,
    "publisher": "પોથી પ્રકાશન",
    "yearPublished": "1",
    "remarks1": ""
  },
  {
    "rate": 350,
    "publisher": "આદર્શ પ્રકાશન",
    "bookType": "New Paper Cover",
    "author": "મીતેશ પરમાર",
    "bookName": "અગ્નિપથના યાત્રી - ડૉ. બાબાસાહેબ આંબેડકર",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "bookId": "78",
    "edition": "",
    "remarks1": "",
    "isbn": "",
    "yearPublished": "",
    "translator": "",
    "language": "ગુજરાતી",
    "createdBy": "Jignesh Upadhyay"
  },
  {
    "language": "ગુજરાતી",
    "author": "સુરેન્દ્ર શુક્લ",
    "remarks1": "નિઃશબ્દ પ્રેમના દિવ્ય પડઘા પાડતી પ્રણયકથા",
    "createdBy": "Jignesh Upadhyay",
    "rate": 225,
    "category": "વાર્તા / વાર્તાઓ",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની પ્રા. લિ.",
    "bookName": "દિવ્યપ્રેમ",
    "isbn": "",
    "bookType": "New Paper Cover",
    "translator": "",
    "edition": "2023",
    "yearPublished": "5",
    "bookId": "79"
  },
  {
    "edition": "1994",
    "isbn": "",
    "bookType": "New Hard Cover",
    "bookName": "આચાર્ય કૃપલાનીની આત્મકથા",
    "publisher": "અમર ઠાકોરલાલ શાહ",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "author": "નીરંજન પારેખ",
    "bookId": "80",
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "",
    "translator": "નગીનદાસ પારેખ",
    "yearPublished": "1",
    "rate": 350,
    "language": "ગુજરાતી"
  },
  {
    "bookType": "New Hard Cover",
    "translator": "",
    "publisher": "યુરેનસ બુક્સ",
    "bookName": "વિસ્મયકારક વિજ્ઞાન - ભાગ ૧",
    "isbn": "",
    "bookId": "81",
    "category": "કમ્પ્યુટર / ટેકનોલોજી / વિજ્ઞાન",
    "createdBy": "Jignesh Upadhyay",
    "rate": 180,
    "edition": "",
    "author": "નગેન્દ્ર વિજય",
    "remarks1": "વાક્યે વાક્યે વિજ્ઞાન પ્રત્યે વિસામે જગાડતું પુસ્તક",
    "language": "ગુજરાતી",
    "yearPublished": ""
  },
  {
    "yearPublished": "9",
    "isbn": "",
    "translator": "",
    "language": "ગુજરાતી",
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "",
    "bookId": "82",
    "category": "કવિતા",
    "bookName": "સારાંશ",
    "publisher": "Image Publication",
    "edition": "2014",
    "bookType": "New Paper Cover",
    "rate": 150,
    "author": "ખલીલ ધનતેજવી"
  },
  {
    "yearPublished": "12",
    "remarks1": "દિલના દરબારમાં હોવાનો હરખ",
    "bookId": "83",
    "isbn": "",
    "language": "ગુજરાતી",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "bookName": "પેશે - ખિદમત",
    "createdBy": "Jignesh Upadhyay",
    "edition": "2025",
    "category": "લેખ",
    "translator": "",
    "author": "હરદ્વાર ગોસ્વામી",
    "rate": 250,
    "bookType": "New Paper Cover"
  },
  {
    "bookType": "New Paper Cover",
    "author": "રક્ષા શુક્લ",
    "yearPublished": "12",
    "isbn": "",
    "category": "પોઝેટીવ એટીટ્યુડ",
    "createdBy": "Jignesh Upadhyay",
    "bookName": "વન્ડરફુલ વુમન",
    "edition": "2025",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "language": "ગુજરાતી",
    "rate": 199,
    "bookId": "84",
    "remarks1": "હાંસિયાથી હરણફાળ",
    "translator": ""
  },
  {
    "isbn": "",
    "bookName": "ચંદ્રકાંત બક્ષીની શ્રેષ્ઠ વાર્તાઓ",
    "category": "વાર્તા / વાર્તાઓ",
    "author": "ચંદ્રકાંત બક્ષી",
    "yearPublished": "",
    "bookType": "New Paper Cover",
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "",
    "edition": "2015",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "language": "ગુજરાતી",
    "translator": "",
    "rate": 170,
    "bookId": "85"
  },
  {
    "isbn": "",
    "edition": "2021",
    "translator": "",
    "bookType": "New Paper Cover",
    "bookName": "રાષ્ટ્ર પુરુષ - ડૉ. બાબા સાહેબ આંબેડકર",
    "author": "કિશોર મકવાણા",
    "category": "લેખ",
    "createdBy": "Jignesh Upadhyay",
    "bookId": "86",
    "publisher": "નમસ્કાર રિસર્ચ ફાઉન્ડેશન",
    "remarks1": "",
    "yearPublished": "",
    "language": "ગુજરાતી",
    "rate": 50
  },
  {
    "bookId": "87",
    "bookName": "વિશ્વાસનું એવરેસ્ટ",
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "edition": "2020",
    "translator": "",
    "category": "પ્રવાસ",
    "isbn": "",
    "bookType": "New Paper Cover",
    "yearPublished": "",
    "remarks1": "રેલવે પાટાથી એવરેસ્ટ સુધીની રોમાંચક કથા",
    "rate": 200,
    "language": "ગુજરાતી",
    "author": "અરુણીમાં સિંહા",
    "createdBy": "Jignesh Upadhyay"
  },
  {
    "translator": "",
    "createdBy": "Jignesh Upadhyay",
    "bookType": "New Hard Cover",
    "author": "નગેન્દ્ર વિજય",
    "rate": 380,
    "bookName": "યુદ્ધ ૭૧",
    "category": "ઈતિહાસ",
    "yearPublished": "5",
    "edition": "2023",
    "publisher": "હર્ષલ પબ્લિકેશન",
    "isbn": "",
    "remarks1": "ભારત-પાક સંગ્રામની સિલસિલાબંધ સત્યકથા",
    "language": "ગુજરાતી",
    "bookId": "88"
  },
  {
    "author": "કિશોર મકવાણા",
    "publisher": "ગુર્જર સાહિત્ય ભવન",
    "isbn": "",
    "remarks1": "",
    "yearPublished": "",
    "language": "ગુજરાતી",
    "createdBy": "Jignesh Upadhyay",
    "bookType": "New Paper Cover",
    "edition": "2025",
    "rate": 270,
    "translator": "",
    "bookId": "89",
    "bookName": "ભારત રત્ન - અટલ બિહારી બાજપેયી",
    "category": "વ્યક્તિ વિષયક"
  },
  {
    "bookType": "New Paper Cover",
    "publisher": "આદર્શ પ્રકાશન",
    "rate": 325,
    "author": "યોગેન્દ્ર જાની",
    "category": "વ્યક્તિ વિષયક",
    "edition": "2023",
    "bookName": "વિશ્વને બદલનારી 100 વૈજ્ઞાનિક શોધો",
    "bookId": "90",
    "isbn": "",
    "yearPublished": "",
    "language": "ગુજરાતી",
    "remarks1": "",
    "createdBy": "Jignesh Upadhyay",
    "translator": ""
  },
  {
    "bookId": "91",
    "bookType": "New Hard Cover",
    "translator": "",
    "isbn": "",
    "category": "કમ્પ્યુટર / ટેકનોલોજી / વિજ્ઞાન",
    "bookName": "વિસ્મયકારક વિજ્ઞાન - ભાગ ૨",
    "createdBy": "Jignesh Upadhyay",
    "publisher": "યુરેનસ બુક્સ",
    "rate": 180,
    "author": "નગેન્દ્ર વિજય",
    "yearPublished": "1",
    "edition": "2006",
    "language": "ગુજરાતી",
    "remarks1": "વાક્યે વાક્યે વિજ્ઞાન પ્રત્યે વિસ્મય જગાડતું પુસ્તક"
  },
  {
    "yearPublished": "",
    "translator": "",
    "bookType": "New Hard Cover",
    "author": "કમળાશંકર પંડયા",
    "isbn": "",
    "bookName": "વેરાન જીવન",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "publisher": "હમેશ મનહર મોદી",
    "edition": "2008",
    "createdBy": "Jignesh Upadhyay",
    "rate": 350,
    "remarks1": "સ્વાતંત્ર્ય સૈનિક કમળાશંકર પંડ્યાની આત્મકથા",
    "language": "ગુજરાતી",
    "bookId": "92"
  },
  {
    "author": "પ્રદીપ મહેતા",
    "bookName": "બરસાના - THE STORY OF RADHE",
    "category": "વાર્તા / વાર્તાઓ",
    "edition": "2021",
    "isbn": "",
    "createdBy": "Jignesh Upadhyay",
    "bookType": "New Hard Cover",
    "publisher": "પ્રદીપ મહેતા",
    "remarks1": "THE STORY OF RADHE",
    "yearPublished": "3",
    "language": "ગુજરાતી",
    "rate": 150,
    "bookId": "93",
    "translator": ""
  },
  {
    "language": "ગુજરાતી",
    "remarks1": "જીવનના જંકશને ઊભેલી લાગણીની વાર્તાઓ",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "bookId": "94",
    "rate": 450,
    "createdBy": "Jignesh Upadhyay",
    "yearPublished": "12",
    "category": "વાર્તા / વાર્તાઓ",
    "isbn": "",
    "author": "રાજ ભાસ્કર",
    "translator": "",
    "bookName": "સ્ટોરી જંકશન",
    "bookType": "New Paper Cover",
    "edition": "2025"
  },
  {
    "isbn": "",
    "yearPublished": "12",
    "remarks1": "BIOGRAPHY OF A TERRORIST",
    "language": "ગુજરાતી",
    "author": "નિકુંજ પટેલ",
    "createdBy": "Jignesh Upadhyay",
    "translator": "",
    "publisher": "જીજ્ઞા પટેલ",
    "bookName": "કસાબનામા - ધરપકડથી દેહાત દંડ સુધીની દાસ્તાન",
    "category": "વ્યક્તિ વિષયક",
    "edition": "2011",
    "bookType": "New Paper Cover",
    "rate": 300,
    "bookId": "95"
  },
  {
    "author": "રસિકબા કેસરિયા",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "bookName": "મહાપરાક્રમી સ્વતંત્રયવીર સાવરકર",
    "createdBy": "Jignesh Upadhyay",
    "bookType": "New Paper Cover",
    "isbn": "",
    "translator": "",
    "edition": "2022",
    "language": "ગુજરાતી",
    "publisher": "આર. આર. શેઠ એન્ડ કંપની પ્રા. લિ.",
    "rate": 250,
    "remarks1": "સાહસથી ભરપૂર અદભૂત વ્યક્તિત્વ, અપ્રતિમ ક્રાંતિવિર, સુરાજ્ય અને સામાજિક સમરસતા માટે સમર્પિત માં ભારતીના અમર સપૂત સ્વાતંત્ર્ય વીર સાવર્કરની જીવનગાથા",
    "bookId": "96",
    "yearPublished": "10"
  },
  {
    "bookType": "New Paper Cover",
    "isbn": "",
    "category": "વાર્તા / વાર્તાઓ",
    "translator": "",
    "publisher": "યુરેનસ બુક્સ",
    "bookId": "97",
    "bookName": "શેરખાન",
    "createdBy": "Jignesh Upadhyay",
    "yearPublished": "4",
    "author": "વિજયગુપ્ત મોર્ય",
    "rate": 120,
    "language": "ગુજરાતી",
    "edition": "2009",
    "remarks1": ""
  },
  {
    "isbn": "",
    "edition": "",
    "language": "ગુજરાતી",
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "",
    "author": "રમણલાલ સોની",
    "bookType": "Old Paper Cover",
    "translator": "",
    "bookId": "98",
    "yearPublished": "",
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "rate": 25,
    "category": "વાર્તા / વાર્તાઓ",
    "bookName": "ગાંઠિયોને ગાંઠિયાની બહેન"
  },
  {
    "language": "ગુજરાતી",
    "isbn": "",
    "createdBy": "Jignesh Upadhyay",
    "bookId": "99",
    "remarks1": "",
    "bookType": "Old Paper Cover",
    "rate": 30,
    "author": "રમણલાલ સોની",
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "yearPublished": "4",
    "category": "વાર્તા / વાર્તાઓ",
    "translator": "",
    "edition": "2006",
    "bookName": "શુભમંગલ ગાંઠવાળી - ભારચિયા લાલ"
  },
  {
    "isbn": "",
    "bookType": "Old Paper Cover",
    "bookId": "100",
    "createdBy": "Jignesh Upadhyay",
    "translator": "",
    "category": "વાર્તા / વાર્તાઓ",
    "edition": "2005",
    "bookName": "નવાબ સાહેબના ચા પાણી",
    "yearPublished": "2",
    "language": "ગુજરાતી",
    "author": "રમણલાલ સોની",
    "remarks1": "",
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "rate": 25
  },
  {
    "language": "ઈંગ્લીશ",
    "publisher": "M M PUBLICATION",
    "isbn": "",
    "author": "MANORAMA",
    "remarks1": "",
    "category": "કમ્પ્યુટર / ટેકનોલોજી / વિજ્ઞાન",
    "translator": "",
    "bookName": "TELL ME WHY - PLANET OCEAN",
    "bookType": "Old Paper Cover",
    "createdBy": "Jignesh Upadhyay",
    "rate": 0,
    "edition": "",
    "bookId": "101",
    "yearPublished": ""
  },
  {
    "translator": "",
    "language": "ગુજરાતી",
    "yearPublished": "2",
    "rate": 25,
    "edition": "2005",
    "createdBy": "Jignesh Upadhyay",
    "bookId": "102",
    "remarks1": "",
    "bookType": "Old Paper Cover",
    "isbn": "",
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "author": "રમણલાલ સોની",
    "category": "વાર્તા / વાર્તાઓ",
    "bookName": "બૂચલો ગધેડો"
  },
  {
    "rate": 25,
    "bookType": "Old Paper Cover",
    "createdBy": "Jignesh Upadhyay",
    "category": "વાર્તા / વાર્તાઓ",
    "bookName": "ચાંદો, સૂરજ અને હાથી",
    "author": "રમણલાલ સોની",
    "translator": "",
    "bookId": "103",
    "edition": "2004",
    "language": "ગુજરાતી",
    "remarks1": "",
    "yearPublished": "2",
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "isbn": ""
  },
  {
    "language": "ગુજરાતી",
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "remarks1": "",
    "bookId": "104",
    "rate": 40,
    "category": "વાર્તા / વાર્તાઓ",
    "isbn": "",
    "bookName": "ભાગવત કથાઓ - ભાગ ૧",
    "author": "રમણલાલ સોની",
    "createdBy": "Jignesh Upadhyay",
    "bookType": "Old Paper Cover",
    "edition": "2006",
    "yearPublished": "",
    "translator": ""
  },
  {
    "rate": 40,
    "remarks1": "",
    "bookId": "105",
    "edition": "2006",
    "language": "ગુજરાતી",
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "bookName": "ભાગવત કથાઓ - ભાગ 3",
    "createdBy": "Jignesh Upadhyay",
    "yearPublished": "",
    "category": "વાર્તા / વાર્તાઓ",
    "author": "રમણલાલ સોની",
    "translator": "",
    "isbn": "",
    "bookType": "Old Paper Cover"
  },
  {
    "createdBy": "Jignesh Upadhyay",
    "author": "હુંદરાજ બલવાની",
    "bookName": "પરોપકારી પ્રશાંત",
    "category": "વાર્તા / વાર્તાઓ",
    "bookType": "Old Paper Cover",
    "rate": 35,
    "isbn": "",
    "remarks1": "",
    "language": "ગુજરાતી",
    "edition": "2012",
    "yearPublished": "11",
    "publisher": "ગુર્જર ગ્રંથરત્ન કાર્યાલય",
    "translator": "",
    "bookId": "106"
  },
  {
    "translator": "",
    "createdBy": "Jignesh Upadhyay",
    "remarks1": "QUESTION - ANSWER",
    "language": "ઈંગ્લીશ",
    "isbn": "",
    "bookId": "107",
    "yearPublished": "",
    "author": "PARAGON",
    "bookName": "ANIMAL KINGDOM",
    "category": "ભાષા / ભણતર / એજ્યુકેશન /",
    "edition": "",
    "publisher": "PaRAGON PUBLISHING INDIA PRIVATE LIMITED",
    "rate": 50,
    "bookType": "New Hard Cover"
  },
  {
    "bookId": "108",
    "bookType": "New Paper Cover",
    "bookName": "લજ્જા સન્યાલ",
    "translator": "",
    "publisher": "સાર્થક પ્રકાશન",
    "category": "નવલકથા",
    "isbn": "",
    "rate": 270,
    "edition": "2024",
    "yearPublished": "1979",
    "createdBy": "Devdutt Thaker",
    "remarks1": "",
    "author": "અશ્વિની ભટ્ટ",
    "language": "ગુજરાતી"
  },
  {
    "rate": 275,
    "language": "ગુજરાતી",
    "remarks1": "",
    "edition": "2023",
    "publisher": "સાર્થક પ્રકાશન",
    "author": "અશ્વિની ભટ્ટ",
    "category": "નવલકથા",
    "createdBy": "Devdutt Thaker",
    "bookName": "શેલજા સાગર",
    "bookId": "109",
    "yearPublished": "1979",
    "translator": "",
    "bookType": "New Paper Cover",
    "isbn": ""
  },
  {
    "yearPublished": "1979",
    "publisher": "સાર્થક પ્રકાશન",
    "bookType": "New Hard Cover",
    "author": "અશ્વિની ભટ્ટ",
    "bookName": "આશકા માંડલ",
    "translator": "",
    "isbn": "",
    "category": "નવલકથા",
    "bookId": "110",
    "edition": "2025",
    "rate": 600,
    "remarks1": "",
    "language": "ગુજરાતી",
    "createdBy": "Devdutt Thaker"
  },
  {
    "createdBy": "Devdutt Thaker",
    "language": "ગુજરાતી",
    "author": "અશ્વિની ભટ્ટ",
    "remarks1": "",
    "isbn": "",
    "yearPublished": "1979",
    "category": "નવલકથા",
    "bookName": "નીરજા ભાર્ગવ",
    "bookType": "New Paper Cover",
    "rate": 250,
    "publisher": "સાર્થક પ્રકાશન",
    "bookId": "111",
    "translator": "",
    "edition": "2024"
  },
  {
    "translator": "",
    "publisher": "સાર્થક પ્રકાશન",
    "bookType": "New Hard Cover",
    "isbn": "",
    "edition": "2025",
    "bookName": "ઓથાર - ભાગ ૦૧",
    "category": "નવલકથા",
    "bookId": "112",
    "yearPublished": "1994",
    "author": "અશ્વિની ભટ્ટ",
    "rate": 750,
    "createdBy": "Devdutt Thaker",
    "remarks1": "",
    "language": "ગુજરાતી"
  },
  {
    "bookType": "New Hard Cover",
    "category": "નવલકથા",
    "edition": "2025",
    "bookName": "ઓથાર - ભાગ ૦૨",
    "publisher": "સાર્થક પ્રકાશન",
    "rate": 750,
    "bookId": "113",
    "isbn": "",
    "translator": "",
    "createdBy": "Devdutt Thaker",
    "author": "અશ્વિની ભટ્ટ",
    "language": "ગુજરાતી",
    "yearPublished": "1994",
    "remarks1": ""
  },
  {
    "rate": 450,
    "yearPublished": "1985",
    "bookType": "New Hard Cover",
    "translator": "",
    "author": "અશ્વિની ભટ્ટ",
    "category": "નવલકથા",
    "createdBy": "Devdutt Thaker",
    "bookName": "ફાંસલો - ભાગ ૦૧",
    "bookId": "114",
    "publisher": "સાર્થક પ્રકાશન",
    "language": "ગુજરાતી",
    "edition": "2024",
    "remarks1": "",
    "isbn": ""
  },
  {
    "remarks1": "",
    "language": "ગુજરાતી",
    "createdBy": "Devdutt Thaker",
    "yearPublished": "1985",
    "bookId": "115",
    "rate": 450,
    "translator": "",
    "author": "અશ્વિની ભટ્ટ",
    "bookName": "ફાંસલો - ભાગ ૦૨",
    "isbn": "",
    "category": "નવલકથા",
    "edition": "2024",
    "bookType": "New Hard Cover",
    "publisher": "સાર્થક પ્રકાશન"
  },
  {
    "category": "નવલકથા",
    "bookName": "કસબ",
    "bookId": "116",
    "bookType": "New Paper Cover",
    "createdBy": "Devdutt Thaker",
    "rate": 175,
    "publisher": "સાર્થક પ્રકાશન",
    "isbn": "",
    "language": "ગુજરાતી",
    "remarks1": "",
    "edition": "2024",
    "translator": "",
    "yearPublished": "1992",
    "author": "અશ્વિની ભટ્ટ"
  },
  {
    "edition": "2021",
    "publisher": "સાર્થક પ્રકાશન",
    "bookId": "117",
    "isbn": "",
    "translator": "",
    "remarks1": "",
    "yearPublished": "1993",
    "language": "ગુજરાતી",
    "bookType": "New Hard Cover",
    "bookName": "અંગાર - ભાગ ૦૧",
    "rate": 634,
    "category": "નવલકથા",
    "author": "અશ્વિની ભટ્ટ",
    "createdBy": "Devdutt Thaker"
  },
  {
    "publisher": "સાર્થક પ્રકાશન",
    "translator": "",
    "bookName": "અંગાર - ભાગ ૦૨",
    "category": "નવલકથા",
    "rate": 633,
    "bookId": "118",
    "yearPublished": "1993",
    "bookType": "New Hard Cover",
    "remarks1": "",
    "author": "અશ્વિની ભટ્ટ",
    "language": "ગુજરાતી",
    "isbn": "",
    "edition": "2021",
    "createdBy": "Devdutt Thaker"
  },
  {
    "edition": "2021",
    "publisher": "સાર્થક પ્રકાશન",
    "translator": "",
    "remarks1": "",
    "rate": 633,
    "language": "ગુજરાતી",
    "author": "અશ્વિની ભટ્ટ",
    "bookName": "અંગાર - ભાગ ૦૩",
    "bookId": "119",
    "category": "નવલકથા",
    "isbn": "",
    "yearPublished": "1993",
    "createdBy": "Devdutt Thaker",
    "bookType": "New Hard Cover"
  },
  {
    "language": "ગુજરાતી",
    "createdBy": "Devdutt Thaker",
    "remarks1": "",
    "bookId": "120",
    "rate": 200,
    "yearPublished": "1997",
    "category": "નવલકથા",
    "isbn": "",
    "bookName": "આયનો",
    "author": "અશ્વિની ભટ્ટ",
    "bookType": "New Paper Cover",
    "edition": "2024",
    "translator": "",
    "publisher": "સાર્થક પ્રકાશન"
  },
  {
    "bookId": "121",
    "remarks1": "",
    "edition": "2024",
    "rate": 534,
    "createdBy": "Devdutt Thaker",
    "language": "ગુજરાતી",
    "translator": "",
    "bookName": "કટિબંધ - ભાગ ૦૧",
    "yearPublished": "1997",
    "category": "નવલકથા",
    "author": "અશ્વિની ભટ્ટ",
    "isbn": "",
    "publisher": "સાર્થક પ્રકાશન",
    "bookType": "New Hard Cover"
  },
  {
    "createdBy": "Devdutt Thaker",
    "category": "નવલકથા",
    "bookName": "કટિબંધ - ભાગ ૦૨",
    "bookId": "122",
    "isbn": "",
    "edition": "2024",
    "bookType": "New Hard Cover",
    "translator": "",
    "yearPublished": "1997",
    "language": "ગુજરાતી",
    "remarks1": "",
    "rate": 533,
    "publisher": "સાર્થક પ્રકાશન",
    "author": "અશ્વિની ભટ્ટ"
  },
  {
    "category": "નવલકથા",
    "author": "અશ્વિની ભટ્ટ",
    "bookName": "કટિબંધ - ભાગ ૦૩",
    "createdBy": "Devdutt Thaker",
    "bookType": "New Hard Cover",
    "rate": 533,
    "language": "ગુજરાતી",
    "publisher": "સાર્થક પ્રકાશન",
    "isbn": "",
    "remarks1": "",
    "translator": "",
    "bookId": "123",
    "yearPublished": "1997",
    "edition": "2024"
  },
  {
    "bookName": "કરામત",
    "translator": "",
    "createdBy": "Devdutt Thaker",
    "bookId": "124",
    "category": "નવલકથા",
    "isbn": "",
    "bookType": "New Paper Cover",
    "remarks1": "",
    "edition": "2024",
    "language": "ગુજરાતી",
    "yearPublished": "1998",
    "rate": 220,
    "publisher": "સાર્થક પ્રકાશન",
    "author": "અશ્વિની ભટ્ટ"
  },
  {
    "language": "ગુજરાતી",
    "createdBy": "Devdutt Thaker",
    "bookId": "125",
    "remarks1": "",
    "rate": 834,
    "edition": "2023",
    "yearPublished": "1999",
    "category": "નવલકથા",
    "bookName": "આખેટ - ભાગ ૦૧",
    "translator": "",
    "isbn": "",
    "bookType": "New Hard Cover",
    "author": "અશ્વિની ભટ્ટ",
    "publisher": "સાર્થક પ્રકાશન"
  },
  {
    "category": "નવલકથા",
    "bookName": "આખેટ - ભાગ ૦૨",
    "createdBy": "Devdutt Thaker",
    "translator": "",
    "bookType": "New Hard Cover",
    "bookId": "126",
    "rate": 833,
    "isbn": "",
    "language": "ગુજરાતી",
    "publisher": "સાર્થક પ્રકાશન",
    "author": "અશ્વિની ભટ્ટ",
    "remarks1": "",
    "yearPublished": "1999",
    "edition": "2023"
  },
  {
    "bookId": "127",
    "edition": "2023",
    "isbn": "",
    "remarks1": "",
    "publisher": "સાર્થક પ્રકાશન",
    "yearPublished": "1999",
    "language": "ગુજરાતી",
    "translator": "",
    "createdBy": "Devdutt Thaker",
    "bookType": "New Hard Cover",
    "bookName": "આખેટ - ભાગ ૦૩",
    "author": "અશ્વિની ભટ્ટ",
    "rate": 833,
    "category": "નવલકથા"
  },
  {
    "bookType": "New Paper Cover",
    "rate": 200,
    "bookId": "128",
    "category": "નવલકથા",
    "translator": "",
    "createdBy": "Devdutt Thaker",
    "bookName": "કમઠાણ",
    "author": "અશ્વિની ભટ્ટ",
    "publisher": "સાર્થક પ્રકાશન",
    "yearPublished": "2001",
    "language": "ગુજરાતી",
    "isbn": "",
    "edition": "2024",
    "remarks1": ""
  },
  {
    "edition": "2025",
    "remarks1": "",
    "yearPublished": "1990",
    "language": "ગુજરાતી",
    "isbn": "",
    "publisher": "સાર્થક પ્રકાશન",
    "translator": "અશ્વિની ભટ્ટ",
    "author": "01.  સંકલિત",
    "bookName": "શ્રેષ્ઠ ભયાનક કથાઓ",
    "createdBy": "Devdutt Thaker",
    "rate": 225,
    "bookId": "129",
    "category": "નવલકથા",
    "bookType": "New Paper Cover"
  },
  {
    "remarks1": "",
    "translator": "",
    "language": "ગુજરાતી",
    "edition": "2014",
    "createdBy": "Devdutt Thaker",
    "bookId": "130",
    "isbn": "",
    "author": "01.  સંકલિત",
    "rate": 50,
    "bookName": "સાર્થક જલસો - ભાગ 3",
    "category": "મેગેઝીન",
    "yearPublished": "1990",
    "publisher": "સાર્થક પ્રકાશન",
    "bookType": "New Paper Cover"
  },
  {
    "yearPublished": "1990",
    "remarks1": "",
    "edition": "2015",
    "language": "ગુજરાતી",
    "rate": 50,
    "author": "01.  સંકલિત",
    "publisher": "સાર્થક પ્રકાશન",
    "bookId": "131",
    "bookName": "સાર્થક જલસો - ભાગ 4",
    "createdBy": "Devdutt Thaker",
    "category": "મેગેઝીન",
    "isbn": "",
    "translator": "",
    "bookType": "New Paper Cover"
  },
  {
    "author": "01.  સંકલિત",
    "publisher": "સાર્થક પ્રકાશન",
    "yearPublished": "1990",
    "language": "ગુજરાતી",
    "isbn": "",
    "remarks1": "",
    "translator": "",
    "bookType": "New Paper Cover",
    "rate": 70,
    "bookId": "132",
    "category": "મેગેઝીન",
    "createdBy": "Devdutt Thaker",
    "edition": "2016",
    "bookName": "સાર્થક જલસો - ભાગ 6"
  },
  {
    "bookName": "સાર્થક જલસો - ભાગ 7",
    "isbn": "",
    "translator": "",
    "category": "મેગેઝીન",
    "createdBy": "Devdutt Thaker",
    "author": "01.  સંકલિત",
    "yearPublished": "1990",
    "bookType": "New Paper Cover",
    "remarks1": "",
    "publisher": "સાર્થક પ્રકાશન",
    "bookId": "133",
    "edition": "2016",
    "language": "ગુજરાતી",
    "rate": 70
  },
  {
    "bookId": "134",
    "translator": "",
    "yearPublished": "1990",
    "category": "મેગેઝીન",
    "bookName": "સાર્થક જલસો - ભાગ 8",
    "createdBy": "Devdutt Thaker",
    "edition": "2017",
    "isbn": "",
    "bookType": "New Paper Cover",
    "language": "ગુજરાતી",
    "publisher": "સાર્થક પ્રકાશન",
    "remarks1": "",
    "rate": 70,
    "author": "01.  સંકલિત"
  },
  {
    "edition": "2017",
    "rate": 70,
    "remarks1": "",
    "yearPublished": "1990",
    "bookId": "135",
    "language": "ગુજરાતી",
    "createdBy": "Devdutt Thaker",
    "author": "01.  સંકલિત",
    "isbn": "",
    "bookType": "New Paper Cover",
    "publisher": "સાર્થક પ્રકાશન",
    "bookName": "સાર્થક જલસો - ભાગ 9",
    "category": "મેગેઝીન",
    "translator": ""
  },
  {
    "author": "01.  સંકલિત",
    "bookName": "સાર્થક જલસો - ભાગ 11",
    "publisher": "સાર્થક પ્રકાશન",
    "category": "મેગેઝીન",
    "rate": 70,
    "bookType": "New Paper Cover",
    "remarks1": "",
    "isbn": "",
    "language": "ગુજરાતી",
    "yearPublished": "1990",
    "edition": "2018",
    "bookId": "136",
    "createdBy": "Devdutt Thaker",
    "translator": ""
  },
  {
    "language": "ગુજરાતી",
    "yearPublished": "1990",
    "createdBy": "Devdutt Thaker",
    "edition": "2019",
    "bookId": "137",
    "remarks1": "",
    "rate": 80,
    "bookType": "New Paper Cover",
    "isbn": "",
    "translator": "",
    "publisher": "સાર્થક પ્રકાશન",
    "author": "01.  સંકલિત",
    "category": "મેગેઝીન",
    "bookName": "સાર્થક જલસો - ભાગ 12"
  },
  {
    "bookId": "138",
    "publisher": "સાર્થક પ્રકાશન",
    "remarks1": "",
    "isbn": "",
    "language": "ગુજરાતી",
    "edition": "2019",
    "rate": 80,
    "translator": "",
    "bookType": "New Paper Cover",
    "bookName": "સાર્થક જલસો - ભાગ 13",
    "yearPublished": "1990",
    "author": "01.  સંકલિત",
    "category": "મેગેઝીન",
    "createdBy": "Devdutt Thaker"
  },
  {
    "rate": 100,
    "author": "01.  સંકલિત",
    "translator": "",
    "createdBy": "Devdutt Thaker",
    "language": "ગુજરાતી",
    "remarks1": "",
    "bookType": "New Paper Cover",
    "yearPublished": "1990",
    "publisher": "સાર્થક પ્રકાશન",
    "category": "મેગેઝીન",
    "bookId": "139",
    "edition": "2020",
    "isbn": "",
    "bookName": "સાર્થક જલસો - ભાગ 14"
  },
  {
    "language": "ગુજરાતી",
    "remarks1": "",
    "edition": "2021",
    "isbn": "",
    "author": "01.  સંકલિત",
    "createdBy": "Devdutt Thaker",
    "category": "મેગેઝીન",
    "rate": 100,
    "bookId": "140",
    "bookName": "સાર્થક જલસો - ભાગ 15",
    "publisher": "સાર્થક પ્રકાશન",
    "yearPublished": "1990",
    "bookType": "New Paper Cover",
    "translator": ""
  },
  {
    "bookId": "141",
    "publisher": "સાર્થક પ્રકાશન",
    "bookName": "સાર્થક જલસો - ભાગ 17",
    "edition": "2022",
    "category": "મેગેઝીન",
    "translator": "",
    "isbn": "",
    "bookType": "New Paper Cover",
    "remarks1": "",
    "rate": 100,
    "language": "ગુજરાતી",
    "yearPublished": "1990",
    "author": "01.  સંકલિત",
    "createdBy": "Devdutt Thaker"
  },
  {
    "publisher": "સાર્થક પ્રકાશન",
    "category": "મેગેઝીન",
    "isbn": "",
    "bookId": "142",
    "bookName": "સાર્થક જલસો - ભાગ 18",
    "yearPublished": "1990",
    "bookType": "New Paper Cover",
    "language": "ગુજરાતી",
    "remarks1": "",
    "translator": "",
    "createdBy": "Devdutt Thaker",
    "edition": "2023",
    "author": "01.  સંકલિત",
    "rate": 100
  },
  {
    "edition": "2023",
    "publisher": "સાર્થક પ્રકાશન",
    "bookType": "New Paper Cover",
    "bookName": "સાર્થક જલસો - ભાગ 19",
    "author": "01.  સંકલિત",
    "rate": 100,
    "category": "મેગેઝીન",
    "isbn": "",
    "bookId": "143",
    "yearPublished": "1990",
    "remarks1": "",
    "translator": "",
    "language": "ગુજરાતી",
    "createdBy": "Devdutt Thaker"
  },
  {
    "publisher": "સાર્થક પ્રકાશન",
    "category": "મેગેઝીન",
    "bookName": "સાર્થક જલસો - ભાગ 20",
    "author": "01.  સંકલિત",
    "edition": "2024",
    "bookType": "New Paper Cover",
    "translator": "",
    "isbn": "",
    "bookId": "144",
    "rate": 100,
    "language": "ગુજરાતી",
    "remarks1": "",
    "yearPublished": "1990",
    "createdBy": "Devdutt Thaker"
  },
  {
    "language": "ગુજરાતી",
    "remarks1": "",
    "bookId": "145",
    "yearPublished": "1990",
    "publisher": "સાર્થક પ્રકાશન",
    "rate": 100,
    "isbn": "",
    "category": "મેગેઝીન",
    "author": "01.  સંકલિત",
    "createdBy": "Devdutt Thaker",
    "bookName": "સાર્થક જલસો - ભાગ 21",
    "bookType": "New Paper Cover",
    "translator": "",
    "edition": "2024"
  },
  {
    "translator": "",
    "yearPublished": "1990",
    "bookName": "સાર્થક જલસો - ભાગ 23",
    "isbn": "",
    "category": "મેગેઝીન",
    "createdBy": "Devdutt Thaker",
    "author": "01.  સંકલિત",
    "bookType": "New Paper Cover",
    "remarks1": "",
    "publisher": "સાર્થક પ્રકાશન",
    "bookId": "146",
    "edition": "2025",
    "language": "ગુજરાતી",
    "rate": 150
  },
  {
    "createdBy": "Devdutt Thaker",
    "language": "ગુજરાતી",
    "yearPublished": "1951",
    "remarks1": "",
    "rate": 500,
    "translator": "મણીભાઈ ભ. દેસાઈ",
    "bookId": "147",
    "edition": "1914",
    "author": "જવાહરલાલ નહેરુ",
    "category": "ઈતિહાસ",
    "bookName": "મારું હિન્દ નું દર્શન",
    "isbn": "",
    "bookType": "New Hard Cover",
    "publisher": "નવજીવન પ્રકાશન મંદિર"
  },
  {
    "isbn": "",
    "translator": "મણીભાઈ ભ. દેસાઈ",
    "author": "જવાહરલાલ નહેરુ",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "bookType": "New Hard Cover",
    "edition": "1914",
    "bookName": "જગતના ઇતિહાસનું સંક્ષિપ્ત રેખાદર્શન",
    "category": "ઈતિહાસ",
    "createdBy": "Devdutt Thaker",
    "remarks1": "",
    "bookId": "148",
    "language": "ગુજરાતી",
    "yearPublished": "1956",
    "rate": 400
  },
  {
    "remarks1": "",
    "createdBy": "Devdutt Thaker",
    "language": "ગુજરાતી",
    "author": "મહાત્મા ગાંધીજી",
    "rate": 60,
    "isbn": "",
    "bookName": "હિન્દ સ્વરાજ",
    "edition": "2025",
    "bookId": "149",
    "category": "ઈતિહાસ",
    "translator": "",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "yearPublished": "1922",
    "bookType": "New Paper Cover"
  },
  {
    "bookId": "150",
    "language": "ગુજરાતી",
    "translator": "",
    "remarks1": "",
    "isbn": "",
    "edition": "2025",
    "yearPublished": "",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "createdBy": "Devdutt Thaker",
    "bookName": "સત્યના પ્રયોગો",
    "rate": 100,
    "author": "મહાત્મા ગાંધીજી",
    "bookType": "New Paper Cover"
  },
  {
    "remarks1": "",
    "edition": "2026",
    "language": "ગુજરાતી",
    "rate": 600,
    "translator": "",
    "author": "રાજમોહન ગાંધી",
    "createdBy": "Devdutt Thaker",
    "bookId": "151",
    "bookName": "સરદાર પટેલ - એક સમર્પિત જીવન",
    "publisher": "નવજીવન પ્રકાશન મંદિર",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "isbn": "",
    "yearPublished": "1994",
    "bookType": "New Hard Cover"
  },
  {
    "language": "ગુજરાતી",
    "remarks1": "",
    "publisher": "સાર્થક પ્રકાશન",
    "translator": "",
    "edition": "7",
    "isbn": "",
    "author": "ઉર્વીશ કોઠારી",
    "yearPublished": "2023",
    "category": "આત્મકથા / જીવન ચરિત્ર",
    "rate": 500,
    "bookName": "સરદાર - સાચો માણસ",
    "bookId": "152",
    "bookType": "New Hard Cover",
    "createdBy": "Devdutt Thaker"
  },
  {
    "category": "નવલકથા",
    "publisher": "પ્રવીણ પ્રકાશન",
    "bookName": "વંશ વારસ - ભાગ 01",
    "isbn": "",
    "author": "હરકિશન મહેતા",
    "bookType": "New Hard Cover",
    "language": "ગુજરાતી",
    "bookId": "153",
    "remarks1": "",
    "yearPublished": "2023",
    "rate": 467,
    "translator": "",
    "edition": "7",
    "createdBy": "Devdutt Thaker"
  },
  {
    "yearPublished": "2023",
    "category": "નવલકથા",
    "bookName": "વંશ વારસ - ભાગ 02",
    "author": "હરકિશન મહેતા",
    "bookType": "New Hard Cover",
    "rate": 467,
    "publisher": "પ્રવીણ પ્રકાશન",
    "language": "ગુજરાતી",
    "createdBy": "Devdutt Thaker",
    "isbn": "",
    "remarks1": "",
    "translator": "",
    "edition": "7",
    "bookId": "154"
  },
  {
    "createdBy": "Devdutt Thaker",
    "bookId": "155",
    "language": "ગુજરાતી",
    "rate": 466,
    "remarks1": "",
    "yearPublished": "2023",
    "edition": "7",
    "translator": "",
    "category": "નવલકથા",
    "bookName": "વંશ વારસ - ભાગ 0૩",
    "author": "હરકિશન મહેતા",
    "isbn": "",
    "bookType": "New Hard Cover",
    "publisher": "પ્રવીણ પ્રકાશન"
  },
  {
    "isbn": "",
    "bookType": "New Hard Cover",
    "yearPublished": "2026",
    "category": "નવલકથા",
    "isIssued": false,
    "edition": "8",
    "createdBy": "Devdutt Thaker",
    "bookName": "જડ ચેતન - ભાગ 01",
    "bookId": "156",
    "publisher": "પ્રવીણ પ્રકાશન",
    "author": "હરકિશન મહેતા",
    "language": "ગુજરાતી",
    "currentIssueDueDate": "",
    "translator": "",
    "rate": 750,
    "currentBorrowerName": "",
    "remarks1": ""
  },
  {
    "language": "ગુજરાતી",
    "createdBy": "Devdutt Thaker",
    "remarks1": "",
    "rate": 750,
    "bookId": "157",
    "edition": "8",
    "author": "હરકિશન મહેતા",
    "category": "નવલકથા",
    "yearPublished": "2026",
    "bookName": "જડ ચેતન - ભાગ 02",
    "isbn": "",
    "translator": "",
    "bookType": "New Hard Cover",
    "publisher": "પ્રવીણ પ્રકાશન"
  },
  {
    "translator": "",
    "yearPublished": "2025",
    "publisher": "પ્રવીણ પ્રકાશન",
    "author": "હરકિશન મહેતા",
    "isbn": "",
    "remarks1": "",
    "language": "ગુજરાતી",
    "rate": 500,
    "bookType": "New Hard Cover",
    "edition": "13",
    "bookName": "જગ્ગા ડાકુના વેરના વળામણા - ભાગ 01",
    "category": "નવલકથા",
    "bookId": "158",
    "createdBy": "Devdutt Thaker"
  },
  {
    "rate": 500,
    "bookId": "159",
    "bookType": "New Hard Cover",
    "bookName": "જગ્ગા ડાકુના વેરના વળામણા - ભાગ 02",
    "yearPublished": "2025",
    "publisher": "પ્રવીણ પ્રકાશન",
    "category": "નવલકથા",
    "edition": "13",
    "createdBy": "Devdutt Thaker",
    "remarks1": "",
    "translator": "",
    "author": "હરકિશન મહેતા",
    "isbn": "",
    "language": "ગુજરાતી"
  },
  {
    "language": "ગુજરાતી",
    "author": "હરકિશન મહેતા",
    "rate": 500,
    "remarks1": "",
    "createdBy": "Devdutt Thaker",
    "edition": "13",
    "publisher": "પ્રવીણ પ્રકાશન",
    "category": "નવલકથા",
    "bookName": "જગ્ગા ડાકુના વેરના વળામણા - ભાગ 0૩",
    "bookId": "160",
    "yearPublished": "2025",
    "bookType": "New Hard Cover",
    "translator": "",
    "isbn": ""
  },
  {
    "language": "ગુજરાતી",
    "bookId": "161",
    "remarks1": "",
    "createdBy": "Devdutt Thaker",
    "rate": 550,
    "isbn": "",
    "category": "નવલકથા",
    "bookName": "મુક્તિ બંધન - ભાગ 01",
    "yearPublished": "2021",
    "edition": "6",
    "bookType": "New Hard Cover",
    "translator": "",
    "author": "હરકિશન મહેતા",
    "publisher": "પ્રવીણ પ્રકાશન"
  },
  {
    "bookId": "162",
    "bookName": "મુક્તિ બંધન - ભાગ 02",
    "edition": "6",
    "createdBy": "Devdutt Thaker",
    "category": "નવલકથા",
    "isbn": "",
    "bookType": "New Hard Cover",
    "remarks1": "",
    "rate": 550,
    "translator": "",
    "language": "ગુજરાતી",
    "publisher": "પ્રવીણ પ્રકાશન",
    "author": "હરકિશન મહેતા",
    "yearPublished": "2021"
  },
  {
    "currentBorrowerName": "",
    "isbn": "978-81-8440-776-1",
    "publisher": "નવભારત સાહિત્ય મંદિર",
    "currentIssueDueDate": "",
    "edition": "13",
    "language": "ગુજરાતી",
    "remarks1": "",
    "author": "ડૉ. શરદ ઠાકર",
    "yearPublished": "2025",
    "bookType": "New Hard Cover",
    "bookId": "163",
    "rate": "555",
    "category": "આત્મકથા / જીવન ચરીત્ર",
    "isIssued": false,
    "bookName": "સિંહપુરુષ",
    "createdBy": "Devdutt Thaker",
    "translator": ""
  }
];

export const EXTRACTED_MASTERS: MasterData = {
  authors: [],
  categories: [],
  translators: [],
  languages: [],
  publishers: [],
  bookTypes: []
};
